@requires COMMAND, IDENTIFIER, STATEMENTS

CITY_ELEMENT      ::= BUILDING_TYPES IDENTIFIER { STATEMENTS BUILDING_ELEMENTS }
BUILDING_ELEMENTS ::=  COMMAND , BUILDING_ELEMENTS | COMMAND |  ε
BUILDING_TYPES    ::= road | building
