@requires IF, INT, FLOAT, ARRAY, ASSIGNMENT, FUNCTION, FUNCTION_CALL, SCOPE, FOR, VAR_DECLARATION, STRING, CHAR

EXPRESSION          ::= EXPRESSION_BITWISE
EXPRESSION_BITWISE  ::= EXPRESSION "|" EXPRESSION_ADDITION | EXPRESSION & EXPRESSION_ADDITION | EXPRESSION_TERM
EXPRESSION_ADDITION ::= EXPRESSION + EXPRESSION_MULTIPLICATION | EXPRESSION - EXPRESSION_MULTIPLICATION | EXPRESSION_TERM
EXPRESSION_TERM     ::= EXPRESSION_TERM * EXPRESSION_POWER | EXPRESSION_TERM / EXPRESSION_POWER | EXPRESSION_POWER
EXPRESSION_POWER    ::= EXPRESSION_PRIMARY ^ EXPRESSION_POWER | EXPRESSION_PRIMARY
EXPRESSION_PRIMARY  ::= ( EXPRESSION ) | ASSIGNMENT | VAR_DECLARATION | FUNCTION | IF | FOR
                        | SCOPE | ARRAY | FUNCTION_CALL | FUNCTION | INT | FLOAT | STRING | CHAR | BOOL
