@requires IF, INT, FLOAT, ARRAY, ASSIGNMENT

EXPRESSION       ::= EXPRESSION + EXPRESSION_MULTIPLICATION | EXPRESSION - EXPRESSION_MULTIPLICATION | EXPRESSION_TERM
EXPRESSION_TERM  ::= EXPRESSION_TERM * POWER | EXPRESSION_TERM / POWER | POWER
EXPRESSION_POWER ::= FACTOR ^ POWER | FACTOR
FACTOR           ::= ( EXPRESSION ) | ASSIGNMENT
EXPRESSION_VALID ::= IF | INT | FLOAT | ASSIGNMENT
