@requires: STATEMENTS, TYPE, IDENTIFIER

FUNCTION      ::= FUNCTION_HEAD FUNCTION_BODY
FUNCTION_HEAD ::= fn IDENTIFIER ( PARAMETERS ) : TYPE | fn IDENTIFIER ( PARAMETERS )
PARAMETERS    ::= PARAMETER , PARAMETERS | PARAMETER | ε
PARAMETER     ::= IDENTIFIER : TYPE
FUNCTION_BODY ::= SCOPE
FUNCTION_CALL ::= IDENTIFIER ( EXPRESSION )
EXPRESSIONS   ::= EXPRESSION , EXPRESSIONS | EXPRESSION | ε
