@requires: STATEMENTS, TYPE

FUNCTION      ::= FUNCTION_HEAD FUNCTION_BODY
FUNCTION_HEAD ::= fn VARIABLE_NAME ( PARAMETERS ) : TYPE | fn VARIABLE_NAME ( PARAMETERS )
PARAMETERS    ::= PARAMETER , PARAMETERS | PARAMETER | ε
PARAMETER     ::= VARIABLE_NAME : TYPE
FUNCTION_BODY ::= { MAYBE_RETURNS }
MAYBE_RETURNS ::= STATEMENTS return | return | STATEMENTS
