@requires: STATEMENTS, TYPE, IDENTIFIER

FUNCTION      ::= FUNCTION_HEAD FUNCTION_BODY
FUNCTION_HEAD ::= fn IDENTIFIER ( PARAMETERS ) : TYPE | fn IDENTIFIER ( PARAMETERS )
PARAMETERS    ::= PARAMETER , PARAMETERS | PARAMETER | ε
PARAMETER     ::= IDENTIFIER : TYPE
FUNCTION_BODY ::= { MAYBE_RETURNS }
MAYBE_RETURNS ::= STATEMENTS return | return | STATEMENTS
