@requires EXPRESSION

GROUP ::= group { GROUP_ELEMENTS }
GROUP_ELEMENTS = GROUP_ELEMENT , GROUP_ELEMENTS | GROUP_ELEMENT | ε

GROUP_ELEMENT = BUILDING | POINT
BUILDING = building STRING EXPRESSION EXPRESSION
POINT = point STRING EXPRESSION
