@requires EXPRESSION, SCOPE

IF      ::= IF_EXPR | IF_EXPR ELSE
IF_EXPR ::= if EXPRESSION SCOPE | if EXPRESSION SCOPE ELSE_IF
ELSE    ::= else SCOPE
ELSE_IF ::= else IF_EXPR ELSE_IF | else IF_EXPR | ε
