@requires IDENTIFIER, TYPE

VAR_DECLARATION      ::= let DECLARATION | const DECLARATION
DECLARATION          ::= IDENTIFIER : TYPE = EXPRESSION | ASSIGNMENT
ASSIGNMENT           ::= IDENTIFIER = EXPRESSION
