const settlements = [
  'Abitanti',
  'Adamovo',
  'Adergas',
  'Adlešiči',
  'Adrijanci',
  'Ajba',
  'Ajbelj',
  'Ajdovščina',
  'Ajševica',
  'Ambrož pod Krvavcem',
  'Ambrus',
  'Andol',
  'Andraž nad Polzelo',
  'Andrejci',
  'Andrejčje',
  'Andrenci',
  'Anhovo',
  'Ankaran',
  'Anovec',
  'Anže',
  'Apače',
  'Apnenik',
  'Apnenik pri Boštanju',
  'Apnenik pri Velikem Trnu',
  'Apno',
  'Arclin',
  'Arčelca',
  'Ardro pod Velikim Trnom',
  'Ardro pri Raki',
  'Arja vas',
  'Armeško',
  'Arnače',
  'Arnovo selo',
  'Artiče',
  'Artiža vas',
  'Artmanja vas',
  'Arto',
  'Artviže',
  'Avber',
  'Avče',
  'Avguštine',
  'Avsa',
  'Aženski Vrh',
  'Babiči',
  'Babinci',
  'Babna Brda',
  'Babna Gora',
  'Babna Polica',
  'Babna Reka',
  'Babni Vrt',
  'Babno Polje',
  'Bač',
  'Bač pri Materiji',
  'Bača pri Modreju',
  'Bača pri Podbrdu',
  'Bačne',
  'Bakovci',
  'Bakrc',
  'Balkovci',
  'Bane',
  'Banja Loka',
  'Banjšice',
  'Banovci',
  'Banuta',
  'Barbana',
  'Baredi',
  'Barislovci',
  'Barizoni',
  'Barka',
  'Bašelj',
  'Bate',
  'Batuje',
  'Bavdek',
  'Bavšica',
  'Beč',
  'Bečaje',
  'Bedenj',
  'Begunje na Gorenjskem',
  'Begunje pri Cerknici',
  'Beka',
  'Bela',
  'Bela Cerkev',
  'Bela Peč',
  'Belavšek',
  'Belca',
  'Belčji Vrh',
  'Bele Vode',
  'Beli Grič',
  'Beli Potok pri Frankolovem',
  'Beli Potok pri Lembergu',
  'Belica',
  'Belo',
  'Belovo',
  'Belski Vrh',
  'Belsko',
  'Belšak',
  'Belšinja vas',
  'Beltinci',
  'Belvedur',
  'Benečija',
  'Benedikt',
  'Benete',
  'Benica',
  'Bereča vas',
  'Beričevo',
  'Berinjak',
  'Berinjek',
  'Berkovci',
  'Berkovski Prelogi',
  'Bertoki',
  'Besnica',
  'Betanja',
  'Betonovo',
  'Bevče',
  'Bevke',
  'Bezena',
  'Bezenškovo Bukovje',
  'Bezgarji',
  'Bezgovica',
  'Bezina',
  'Beznovci',
  'Bezovica',
  'Bezovje nad Zrečami',
  'Bezovje pri Šentjurju',
  'Bezuljak',
  'Bič',
  'Bičje',
  'Biljana',
  'Bilje',
  'Binkelj',
  'Birčna vas',
  'Birna vas',
  'Biserjane',
  'Bistra',
  'Bistrica',
  'Bistrica ob Dravi',
  'Bistrica ob Sotli',
  'Bistrica pri Tržiču',
  'Bistričica',
  'Biš',
  'Bišče',
  'Bišečki Vrh',
  'Biška vas',
  'Bitiče',
  'Bitnja vas',
  'Bitnje',
  'Bizeljska vas',
  'Bizeljsko',
  'Blagovica',
  'Blaguš',
  'Blanca',
  'Blate',
  'Blatna Brezovica',
  'Blatni Vrh',
  'Blatnik pri Črmošnjicah',
  'Blatnik pri Črnomlju',
  'Blatno',
  'Blato',
  'Blečji Vrh',
  'Bled',
  'Blejska Dobrava',
  'Bločice',
  'Blodnik',
  'Bloška Polica',
  'Boben',
  'Bobovek',
  'Bobovo pri Ponikvi',
  'Bobovo pri Šmarju',
  'Bočaji',
  'Bočkovo',
  'Bočna',
  'Bodešče',
  'Bodislavci',
  'Bodkovci',
  'Bodonci',
  'Bodovlje',
  'Bodrež',
  'Bodrišna vas',
  'Boga vas',
  'Bogenšperk',
  'Boginja vas',
  'Bogneča vas',
  'Bogo',
  'Bogojina',
  'Boharina',
  'Bohinjska Bela',
  'Bohinjska Bistrica',
  'Bohinjska Češnjica',
  'Bohova',
  'Bojanci',
  'Bojanja vas',
  'Bojanji Vrh',
  'Bojsno',
  'Bojtina',
  'Bokrači',
  'Boldraž',
  'Bolečka vas',
  'Bolehnečici',
  'Boletina',
  'Boltija',
  'Bonini',
  'Boračeva',
  'Boreci',
  'Boreča',
  'Borejci',
  'Boričevo',
  'Borjana',
  'Borje',
  'Borje pri Mlinšah',
  'Borovak pri Podkumu',
  'Borovak pri Polšniku',
  'Borovci',
  'Borovec pri Karlovici',
  'Borovec pri Kočevski Reki',
  'Borovnica',
  'Boršt',
  'Boršt pri Dvoru',
  'Bosljiva Loka',
  'Bošamarin',
  'Boštanj',
  'Boštetje',
  'Botričnica',
  'Bovec',
  'Bovše',
  'Božakovo',
  'Božič Vrh',
  'Božje',
  'Bračna vas',
  'Branik',
  'Brankovo',
  'Branoslavci',
  'Braslovče',
  'Bratislavci',
  'Bratnice',
  'Bratonci',
  'Bratonečice',
  'Brce',
  'Brda',
  'Brdarci',
  'Brdce',
  'Brdce nad Dobrno',
  'Brdice pri Kožbani',
  'Brdice pri Neblem',
  'Brdinje',
  'Brdo',
  'Brdo pri Lukovici',
  'Brebovnica',
  'Brecljevo',
  'Breg',
  'Breg ob Bistrici',
  'Breg ob Kokri',
  'Breg ob Savi',
  'Breg pri Borovnici',
  'Breg pri Dobu',
  'Breg pri Golem Brdu',
  'Breg pri Kočevju',
  'Breg pri Komendi',
  'Breg pri Konjicah',
  'Breg pri Litiji',
  'Breg pri Polzeli',
  'Breg pri Ribnici na Dol.',
  'Breg pri Sinjem Vrhu',
  'Breg pri Temenici',
  'Breg pri Zagradcu',
  'Brege',
  'Breginj',
  'Brekovice',
  'Brengova',
  'Bresnica',
  'Brest',
  'Brestanica',
  'Bresternica',
  'Brestje',
  'Brestovec',
  'Brestovica pri Komnu',
  'Brestovica pri Povirju',
  'Breška vas',
  'Breza',
  'Brezen',
  'Brezje',
  'Brezje nad Kamnikom',
  'Brezje ob Slomu',
  'Brezje pod Nanosom',
  'Brezje pri Bojsnem',
  'Brezje pri Dobjem',
  'Brezje pri Dobrovi',
  'Brezje pri Dobu',
  'Brezje pri Dovškem',
  'Brezje pri Grosupljem',
  'Brezje pri Kumpolju',
  'Brezje pri Lekmarju',
  'Brezje pri Lipoglavu',
  'Brezje pri Ločah',
  'Brezje pri Oplotnici',
  'Brezje pri Podplatu',
  'Brezje pri Poljčanah',
  'Brezje pri Raki',
  'Brezje pri Rožnem Dolu',
  'Brezje pri Senušah',
  'Brezje pri Slov. Bistrici',
  'Brezje pri Šentjerneju',
  'Brezje pri Trebelnem',
  'Brezje pri Tržiču',
  'Brezje pri Veliki Dolini',
  'Brezje pri Vinjem Vrhu',
  'Brezje v Podbočju',
  'Brezni Vrh',
  'Breznica',
  'Breznica pod Lubnikom',
  'Breznica pri Žireh',
  'Breznik',
  'Brezno',
  'Brezova',
  'Brezova Reber',
  'Brezova Reber pri Dvoru',
  'Brezovci',
  'Brezovec',
  'Brezovec - del',
  'Brezovec pri Polju',
  'Brezovec pri Rogatcu',
  'Brezovi Dol',
  'Brezovica',
  'Brezovica na Bizeljskem',
  'Brezovica pri Borovnici',
  'Brezovica pri Črmošnjicah',
  'Brezovica pri Dobu',
  'Brezovica pri Gradinu',
  'Brezovica pri Ljubljani',
  'Brezovica pri Medvodah',
  'Brezovica pri Metliki',
  'Brezovica pri Mirni',
  'Brezovica pri Predgradu',
  'Brezovica pri Stopičah',
  'Brezovica pri Trebelnem',
  'Brezovica pri Zlatem Polju',
  'Brezovica v Podbočju',
  'Brezovk',
  'Brezovo',
  'Brezovo Brdo',
  'Brezovska Gora',
  'Brezula',
  'Breže',
  'Brežec pri Divači',
  'Brežice',
  'Brglez',
  'Briga',
  'Brinje',
  'Brinovščica',
  'Briše',
  'Briše pri Polhovem Gradcu',
  'Britof',
  'Brje',
  'Brje pri Komnu',
  'Brje pri Koprivi',
  'Brlog',
  'Brlog - del',
  'Brnica',
  'Brod',
  'Brod v Podbočju',
  'Brode',
  'Brodnice',
  'Brsnik',
  'Brstnik',
  'Brstovec',
  'Brstovnica',
  'Bršlenovica',
  'Bruhanja vas',
  'Bruna vas',
  'Brunk',
  'Brunška Gora',
  'Brunšvik',
  'Brvace',
  'Brvi',
  'Buč',
  'Buče',
  'Bučečovci',
  'Bučerca',
  'Bučka',
  'Bučkovci',
  'Budanje',
  'Budganja vas',
  'Budihni',
  'Budinci',
  'Budna vas',
  'Buje',
  'Bukošek',
  'Bukov Vrh',
  'Bukov Vrh nad Visokim',
  'Bukovca',
  'Bukovci',
  'Bukovec',
  'Bukovec pri Poljanah',
  'Bukovica',
  'Bukovica pri Litiji',
  'Bukovica pri Vodicah',
  'Bukovje',
  'Bukovje pri Slivnici',
  'Bukovje v Babni Gori',
  'Bukovlje',
  'Bukovnica',
  'Bukovo',
  'Bukovska vas',
  'Bukovski Vrh',
  'Bukovščica',
  'Bukovžlak',
  'Bunčani',
  'Bušeča vas',
  'Bušinec',
  'Bušinja vas',
  'Butajnova',
  'Butari',
  'Butoraj',
  'Cajnarje',
  'Cankova',
  'Cegelnica',
  'Ceglo',
  'Celestrina',
  'Celine',
  'Celje',
  'Cenkova',
  'Centa',
  'Cepki',
  'Cerej',
  'Cerina',
  'Cerkljanska Dobrava',
  'Cerkljanski Vrh',
  'Cerklje na Gorenjskem',
  'Cerklje ob Krki',
  'Cerknica',
  'Cerkno',
  'Cerkvenjak',
  'Cerkvišče',
  'Cerov Log',
  'Cerovec',
  'Cerovec pod Bočem',
  'Cerovec pri Črešnjevcu',
  'Cerovec pri Šmarju',
  'Cerovec pri Trebelnem',
  'Cerovec Stanka Vraza',
  'Cerovica',
  'Cerovo',
  'Ceršak',
  'Cesta',
  'Ceste',
  'Cetore',
  'Cezanjevci',
  'Cezlak',
  'Ciglence',
  'Cigonca',
  'Cikava',
  'Ciringa',
  'Cirje',
  'Cirknica',
  'Cirkovce',
  'Cirkulane',
  'Cirkuše',
  'Cirkuše v Tuhinju',
  'Cirnik',
  'Cmereška Gorca',
  'Cogetinci',
  'Col',
  'Coljava',
  'Colnarji',
  'Crngrob',
  'Cuber',
  'Cundrovec',
  'Cunkovci',
  'Curnovec',
  'Cven',
  'Cvetkovci',
  'Cvišlerji',
  'Čabrače',
  'Čača vas',
  'Čadovlje',
  'Čadovlje pri Tržiču',
  'Čadram',
  'Čadramska vas',
  'Čadraže',
  'Čadrg',
  'Čagona',
  'Čagošče',
  'Čakova',
  'Čanje',
  'Čateška Gora',
  'Čatež',
  'Čatež ob Savi',
  'Čebine',
  'Čeče - del',
  'Čedem',
  'Čehovini',
  'Čekovnik',
  'Čelevec',
  'Čelje',
  'Čelovnik',
  'Čemše',
  'Čemšenik',
  'Čentiba',
  'Čentur',
  'Čepinci',
  'Čeplez',
  'Čeplje',
  'Čepno',
  'Čepovan',
  'Čepulje',
  'Čermožiše',
  'Černelavci',
  'Češča vas',
  'Češenik',
  'Češnjevek',
  'Češnjica',
  'Češnjica pri Kropi',
  'Češnjice',
  'Češnjice pri Moravčah',
  'Češnjice pri Trebelnem',
  'Češnjice pri Zagradcu',
  'Češnjice v Tuhinju',
  'Četena Ravan',
  'Četež pri Strugah',
  'Četež pri Turjaku',
  'Čezsoča',
  'Čežarji',
  'Čiginj',
  'Čikečka vas',
  'Čilpah',
  'Čimerno',
  'Činžat',
  'Čipnje',
  'Čisti Breg',
  'Čohovo',
  'Čolnica',
  'Čolnišče',
  'Črenšovci',
  'Čreškova',
  'Črešnjevci',
  'Črešnjevec',
  'Črešnjevec ob Bistrici',
  'Črešnjevec ob Dravi',
  'Črešnjevec pri Dragatušu',
  'Črešnjevec pri Oštrcu',
  'Črešnjevec pri Semiču',
  'Črešnjice',
  'Črešnjice nad Pijavškim',
  'Črešnjice pri Cerkljah',
  'Črešnova',
  'Čreta',
  'Čreta pri Kokarjah',
  'Čretež pri Krškem',
  'Čretvež',
  'Črmlja',
  'Črmljenšak',
  'Črmošnjice',
  'Črmošnjice pri Stopičah',
  'Črna na Koroškem',
  'Črna pri Kamniku',
  'Črna vas',
  'Črnci',
  'Črnec',
  'Črneča vas',
  'Črneče',
  'Črneška Gora',
  'Črni Kal',
  'Črni Potok',
  'Črni Potok pri Dragi',
  'Črni Potok pri Kočevju',
  'Črni Potok pri Vel. Laščah',
  'Črni Vrh',
  'Črni Vrh v Tuhinju',
  'Črniče',
  'Črnivec',
  'Črnolica',
  'Črnomelj',
  'Črnotiče',
  'Črnova',
  'Čučja Mlaka',
  'Čudno selo',
  'Čurile',
  'Čušperk',
  'Čužnja vas',
  'Daber',
  'Dalce',
  'Daljni Vrh',
  'Dalnje Njive',
  'Damelj',
  'Dane',
  'Dane pri Divači',
  'Dane pri Sežani',
  'Dankovci',
  'Davča',
  'Debeče',
  'Debenec',
  'Debeni',
  'Debro',
  'Dečina',
  'Dečja vas',
  'Dečja vas pri Zagradcu',
  'Dečno selo',
  'Dedna Gora',
  'Dedni Dol',
  'Dedni Vrh',
  'Dedni Vrh pri Vojniku',
  'Dednik',
  'Dednja vas',
  'Dekani',
  'Dekmanca',
  'Delač',
  'Delnice',
  'Depala vas',
  'Desenci',
  'Desinec',
  'Deskle',
  'Deskova vas',
  'Desnjak',
  'Destrnik',
  'Dešeča vas',
  'Dešen',
  'Devina',
  'Dežno pri Makolah',
  'Dežno pri Podlehniku',
  'Dilce',
  'Dilici',
  'Divača',
  'Divči',
  'Dob',
  'Dob pri Šentvidu',
  'Dobe',
  'Dobec',
  'Dobeno',
  'Dobindol',
  'Dobja vas',
  'Dobje',
  'Dobje pri Lesičnem',
  'Dobje pri Planini',
  'Doblar',
  'Doblatina',
  'Dobletina',
  'Dobležiče',
  'Dobliče',
  'Doblička Gora',
  'Dobova',
  'Dobovec',
  'Dobovec pri Ponikvi',
  'Dobovec pri Rogatcu',
  'Dobovica',
  'Dobovlje',
  'Dobovo',
  'Dobrava',
  'Dobrava ob Krki',
  'Dobrava pod Rako',
  'Dobrava pri Konjicah',
  'Dobrava pri Kostanjevici',
  'Dobrava pri Stični',
  'Dobrava pri Škocjanu',
  'Dobravica',
  'Dobravica pri Vel. Gabru',
  'Dobravlje',
  'Dobravšce',
  'Dobrič',
  'Dobrije',
  'Dobrina',
  'Dobriša vas',
  'Dobriška vas',
  'Dobrljevo',
  'Dobrna',
  'Dobrnež',
  'Dobrnič',
  'Dobro Polje',
  'Dobropolje',
  'Dobrova',
  'Dobrova pri Dravogradu',
  'Dobrova pri Prihovi',
  'Dobrovce',
  'Dobrovlje',
  'Dobrovlje pri Mozirju',
  'Dobrovnik',
  'Dobrovo',
  'Dobrovščak',
  'Dobruša',
  'Dobruška vas',
  'Dogoše',
  'Doklece',
  'Dokležovje',
  'Dol',
  'Dol pod Gojko',
  'Dol pri Borovnici',
  'Dol pri Hrastniku',
  'Dol pri Hrastovljah',
  'Dol pri Laškem',
  'Dol pri Ljubljani',
  'Dol pri Pristavi',
  'Dol pri Stopercah',
  'Dol pri Šmarjeti',
  'Dol pri Šmarju',
  'Dol pri Trebnjem',
  'Dol pri Vogljah',
  'Dolanci',
  'Dolane',
  'Dole',
  'Dole pod Sv. Trojico',
  'Dole pri Krašcah',
  'Dole pri Litiji',
  'Dole pri Polici',
  'Dole pri Škofljici',
  'Dolena',
  'Dolenci',
  'Dolenčice',
  'Dolenja Brezovica',
  'Dolenja Dobrava',
  'Dolenja Lepa vas',
  'Dolenja Nemška vas',
  'Dolenja Pirošica',
  'Dolenja Podgora',
  'Dolenja Ravan',
  'Dolenja Stara vas',
  'Dolenja Trebuša',
  'Dolenja vas',
  'Dolenja vas pri Artičah',
  'Dolenja vas pri Čatežu',
  'Dolenja vas pri Črnomlju',
  'Dolenja vas pri Krškem',
  'Dolenja vas pri Mirni Peči',
  'Dolenja vas pri Polhovem Gradcu',
  'Dolenja vas pri Polici',
  'Dolenja vas pri Raki',
  'Dolenja vas pri Temenici',
  'Dolenja Žetina',
  'Dolenjci',
  'Dolenje',
  'Dolenje Brdo',
  'Dolenje Dole',
  'Dolenje Gradišče pri Šentj.',
  'Dolenje Grčevje',
  'Dolenje Jesenice',
  'Dolenje Jezero',
  'Dolenje Kamenje',
  'Dolenje Kamenje pri Dobrniču',
  'Dolenje Karteljevo',
  'Dolenje Kronovo',
  'Dolenje Laknice',
  'Dolenje Lakovnice',
  'Dolenje Medvedje selo',
  'Dolenje Mokro Polje',
  'Dolenje Otave',
  'Dolenje Podpoljane',
  'Dolenje Poljane',
  'Dolenje Polje',
  'Dolenje Ponikve',
  'Dolenje pri Jelšanah',
  'Dolenje Radulje',
  'Dolenje Selce',
  'Dolenje Skopice',
  'Dolenje Sušice',
  'Dolenje Vrhpolje',
  'Dolenje Zabukovje',
  'Dolenji Boštanj',
  'Dolenji Globodol',
  'Dolenji Lazi',
  'Dolenji Leskovec',
  'Dolenji Maharovec',
  'Dolenji Novaki',
  'Dolenji Podboršt',
  'Dolenji Podboršt pri Treb.',
  'Dolenji Podšumberk',
  'Dolenji Radenci',
  'Dolenji Suhadol',
  'Dolenji Suhor pri Vinici',
  'Dolenji Vrh',
  'Dolenjske Toplice',
  'Dolga Brda',
  'Dolga Gora',
  'Dolga Njiva pri Šentlovren.',
  'Dolga Poljana',
  'Dolga Raka',
  'Dolga vas',
  'Dolge Njive',
  'Dolgi Laz',
  'Dolgi Vrh',
  'Dolgo Brdo',
  'Dolgo Brdo pri Mlinšah',
  'Dolgovaške Gorice',
  'Dolič',
  'Dolina',
  'Dolina pri Lendavi',
  'Dolje',
  'Dolnja Bistrica',
  'Dolnja Bitnja',
  'Dolnja Briga',
  'Dolnja Košana',
  'Dolnja Lokvica',
  'Dolnja Paka',
  'Dolnja Počehova',
  'Dolnja Prekopa',
  'Dolnja Stara vas',
  'Dolnja Težka Voda',
  'Dolnje Brezovo',
  'Dolnje Cerovo',
  'Dolnje Dobravice',
  'Dolnje Impolje',
  'Dolnje Ležeče',
  'Dolnje Ložine',
  'Dolnje Mraševo',
  'Dolnje Orle',
  'Dolnje Prapreče',
  'Dolnje Retje',
  'Dolnje Vreme',
  'Dolnji Ajdovec',
  'Dolnji Kot',
  'Dolnji Križ',
  'Dolnji Lakoš',
  'Dolnji Slaveči',
  'Dolnji Suhor pri Metliki',
  'Dolnji Vrh',
  'Dolnji Zemon',
  'Dolsko',
  'Dol-Suha',
  'Dolšce',
  'Dolščaki',
  'Dolž',
  'Domajinci',
  'Domanjševci',
  'Dombrava',
  'Domžale',
  'Donačka Gora',
  'Dorfarje',
  'Dornava',
  'Dornberk',
  'Dornice',
  'Doropolje',
  'Doslovče',
  'Dovje',
  'Dovško',
  'Dovže',
  'Draga',
  'Draga pri Sinjem Vrhu',
  'Draga pri Šentrupertu',
  'Dragatuš',
  'Drage',
  'Dragočajna',
  'Dragomelj',
  'Dragomer',
  'Dragomilo',
  'Dragomlja vas',
  'Dragonja',
  'Dragonja vas',
  'Dragoši',
  'Dragotinci',
  'Dragovanja vas',
  'Dragovica',
  'Dragovič',
  'Dragovšek',
  'Dragučova',
  'Drakovci',
  'Drakšl',
  'Drama',
  'Dramlja',
  'Dramlje',
  'Drankovec',
  'Drašča vas',
  'Drašiči',
  'Dravci',
  'Dravče',
  'Dravinjski Vrh',
  'Dravograd',
  'Dravski Dvor',
  'Draža vas',
  'Dražen Vrh - del',
  'Draženci',
  'Draževnik',
  'Dražgoše',
  'Dražica',
  'Drbetinci',
  'Drča',
  'Drečji Vrh',
  'Dren',
  'Drenik',
  'Drenje',
  'Drenov Grič',
  'Drenovec',
  'Drenovec pri Bukovju',
  'Drenovec pri Leskovcu',
  'Drensko Rebro',
  'Drešinja vas',
  'Drevenik',
  'Drežnica',
  'Drežnik',
  'Drežniške Ravne',
  'Drganja Sela',
  'Drnovk',
  'Drnovo',
  'Drobinsko',
  'Drobočnik',
  'Drobtinci',
  'Drožanje',
  'Drskovče',
  'Drstelja',
  'Drtija',
  'Drumlažno',
  'Drušče',
  'Družina',
  'Družinska vas',
  'Drvanja',
  'Dule',
  'Dunaj',
  'Dupeljne',
  'Duplje',
  'Dutovlje',
  'Dvor',
  'Dvor pri Polhovem Gradcu',
  'Dvorce',
  'Dvori',
  'Dvorjane',
  'Dvorje',
  'Dvorska vas',
  'Erzelj',
  'Fabci',
  'Fala',
  'Famlje',
  'Fara',
  'Farovec',
  'Fijeroga',
  'Fikšinci',
  'Filipčje Brdo',
  'Filovci',
  'Finkovo',
  'Flekušek',
  'Florjan',
  'Florjan pri Gornjem Gradu',
  'Fojana',
  'Fokovci',
  'Forme',
  'Formin',
  'Fošt',
  'Frajhajm',
  'Fram',
  'Frankolovo',
  'Frankovci',
  'Frluga',
  'Froleh',
  'Fučkovci',
  'Fužina',
  'Fužine',
  'Gaberje',
  'Gaberke',
  'Gabernik',
  'Gabrc',
  'Gabrce',
  'Gabrče',
  'Gabrijele',
  'Gabrje',
  'Gabrje pod Limbarsko Goro',
  'Gabrje pod Špilkom',
  'Gabrje pri Dobovi',
  'Gabrje pri Ilovi Gori',
  'Gabrje pri Jančah',
  'Gabrje pri Soteski',
  'Gabrje pri Stični',
  'Gabrk',
  'Gabrnik',
  'Gabrno',
  'Gabrovčec',
  'Gabrovec pri Dramljah',
  'Gabrovec pri Kostrivnici',
  'Gabrovica pri Črnem Kalu',
  'Gabrovica pri Komnu',
  'Gabrovka',
  'Gabrovka pri Zagradcu',
  'Gabrovlje',
  'Gabrovnica',
  'Gabrovnik',
  'Gabrovo',
  'Gabrska Gora',
  'Gabrsko',
  'Gabrška Gora',
  'Gačnik',
  'Gaj',
  'Gaj nad Mariborom',
  'Gajevci',
  'Gajniče',
  'Gajševci',
  'Galantiči',
  'Galicija',
  'Galušak',
  'Gančani',
  'Gašpinovo',
  'Gatina',
  'Gavce',
  'Gazice',
  'Gažon',
  'Gederovci',
  'Genterovci',
  'Gerečja vas',
  'Gerlinci',
  'Geršiči',
  'Gibina',
  'Gladomes',
  'Glem',
  'Glina',
  'Glinek',
  'Glinje',
  'Glinsko',
  'Globel',
  'Globočdol',
  'Globoče',
  'Globočice',
  'Globočice pri Kostanjevici',
  'Globoka',
  'Globoko',
  'Globoko ob Dravinji',
  'Globoko pri Šmarju',
  'Glogov Brod',
  'Glogovica',
  'Gmajna',
  'Gmajnica',
  'Gobnik',
  'Gobovce',
  'Goče',
  'Gočova',
  'Godemarci',
  'Godeninci',
  'Godešič',
  'Godič',
  'Godičevo',
  'Godnje',
  'Godovič',
  'Gojače',
  'Golac',
  'Golavabuka',
  'Golče',
  'Golek',
  'Golek pri Vinici',
  'Goli Vrh',
  'Golica',
  'Golice',
  'Golišče',
  'Goljek',
  'Goljevica',
  'Golnik',
  'Golo',
  'Golo Brdo',
  'Golobinjek',
  'Golobinjek ob Sotli',
  'Golobinjek pri Planini',
  'Golušnik',
  'Gombišče',
  'Gomila',
  'Gomila pri Kogu',
  'Gomilci',
  'Gomilica',
  'Gomilsko',
  'Gonjače',
  'Gora',
  'Gora pri Komendi',
  'Gora pri Pečah',
  'Gorca',
  'Gorče',
  'Gore',
  'Goreljce',
  'Goreljek',
  'Gorenja Brezovica',
  'Gorenja Dobrava',
  'Gorenja Gomila',
  'Gorenja Kanomlja',
  'Gorenja Lepa vas',
  'Gorenja Nemška vas',
  'Gorenja Pirošica',
  'Gorenja Podgora',
  'Gorenja Ravan',
  'Gorenja Stara vas',
  'Gorenja Trebuša',
  'Gorenja vas',
  'Gorenja vas - Reteče',
  'Gorenja vas pri Čatežu',
  'Gorenja vas pri Leskovcu',
  'Gorenja vas pri Mirni',
  'Gorenja vas pri Mokronogu',
  'Gorenja vas pri Polici',
  'Gorenja vas pri Šmarjeti',
  'Gorenja Žaga',
  'Gorenja Žetina',
  'Gorenjci pri Adlešičih',
  'Gorenje',
  'Gorenje Blato',
  'Gorenje Brdo',
  'Gorenje Brezovo',
  'Gorenje Dole',
  'Gorenje Gradišče',
  'Gorenje Gradišče pri Šentj.',
  'Gorenje Grčevje',
  'Gorenje Jelenje',
  'Gorenje Jesenice',
  'Gorenje Jezero',
  'Gorenje Kališče',
  'Gorenje Kamence',
  'Gorenje Kamenje',
  'Gorenje Kamenje pri Dobrniču',
  'Gorenje Karteljevo',
  'Gorenje Kronovo',
  'Gorenje Laknice',
  'Gorenje Lakovnice',
  'Gorenje Medvedje selo',
  'Gorenje Mokro Polje',
  'Gorenje Mraševo',
  'Gorenje Nekovo',
  'Gorenje Otave',
  'Gorenje Podpoljane',
  'Gorenje Polje',
  'Gorenje Ponikve',
  'Gorenje pri Divači',
  'Gorenje pri Zrečah',
  'Gorenje Radulje',
  'Gorenje Selce',
  'Gorenje Skopice',
  'Gorenje Sušice',
  'Gorenje Vrhpolje',
  'Gorenje Zabukovje',
  'Gorenji Globodol',
  'Gorenji Lazi',
  'Gorenji Leskovec',
  'Gorenji Log',
  'Gorenji Maharovec',
  'Gorenji Mokronog',
  'Gorenji Novaki',
  'Gorenji Podboršt',
  'Gorenji Podboršt pri V. Loki',
  'Gorenji Podšumberk',
  'Gorenji Potok',
  'Gorenji Radenci',
  'Gorenji Suhadol',
  'Gorenji vrh pri Dobrniču',
  'Gorenji Vrsnik',
  'Gorenjski Vrh',
  'Gorica',
  'Gorica na Medvedjeku',
  'Gorica pri Dobjem',
  'Gorica pri Oplotnici',
  'Gorica pri Raztezu',
  'Gorica pri Slivnici',
  'Gorica pri Šmartnem',
  'Goriča vas',
  'Goričak',
  'Goričane',
  'Goriče',
  'Goriče pri Famljah',
  'Goričica',
  'Goričica pod Krimom',
  'Goričica pri Ihanu',
  'Goričica pri Moravčah',
  'Goričice',
  'Goriška Gora',
  'Goriška vas',
  'Goriška vas pri Škocjanu',
  'Goriški Vrh',
  'Gorišnica',
  'Gorjane',
  'Gorjansko',
  'Gorje',
  'Gorjuša',
  'Gorjuše',
  'Gornja Bistrica',
  'Gornja Bitnja',
  'Gornja Briga',
  'Gornja Košana',
  'Gornja Lokvica',
  'Gornja Paka',
  'Gornja Prekopa',
  'Gornja Radgona',
  'Gornja Stara vas',
  'Gornja Težka Voda',
  'Gornja vas',
  'Gornje Brezovo',
  'Gornje Cerovo',
  'Gornje Dobravice',
  'Gornje Impolje',
  'Gornje Laze',
  'Gornje Ležeče',
  'Gornje Ložine',
  'Gornje Orle',
  'Gornje Pijavško',
  'Gornje Prapreče',
  'Gornje Ravne',
  'Gornje Retje',
  'Gornje Vreme',
  'Gornji Ajdovec',
  'Gornji Črnci',
  'Gornji Dolič',
  'Gornji Grad',
  'Gornji Ig',
  'Gornji Ivanjci',
  'Gornji Ključarovci',
  'Gornji Kot',
  'Gornji Križ',
  'Gornji Lakoš',
  'Gornji Lenart',
  'Gornji Petrovci',
  'Gornji Rogatec',
  'Gornji Slaveči',
  'Gornji Suhor pri Metliki',
  'Gornji Suhor pri Vinici',
  'Gornji Vrh',
  'Gornji Zemon',
  'Goropeke',
  'Gorski Vrh',
  'Gortina',
  'Gosteče',
  'Gostinca',
  'Gotenc',
  'Gotenica',
  'Gotovlje',
  'Govce',
  'Goveji Dol',
  'Govejk',
  'Gozd',
  'Gozd Martuljek',
  'Gozdec',
  'Gozd-Reka',
  'Grabče',
  'Grabe',
  'Grabe pri Ljutomeru',
  'Graben',
  'Grabonoš',
  'Grabonoški Vrh',
  'Grabrovec',
  'Grabšinci',
  'Gračič',
  'Gračišče',
  'Gračnica',
  'Grad',
  'Gradac',
  'Gradec',
  'Gradenc',
  'Gradenje',
  'Gradenšak',
  'Gradež',
  'Gradiček',
  'Gradin',
  'Gradišča',
  'Gradiščak',
  'Gradišče',
  'Gradišče - K. o. Št. Lovrenc',
  'Gradišče na Kozjaku',
  'Gradišče nad Prvačino',
  'Gradišče pri Divači',
  'Gradišče pri Litiji',
  'Gradišče pri Lukovici',
  'Gradišče pri Materiji',
  'Gradišče pri Raki',
  'Gradišče pri Štjaku',
  'Gradišče pri Trebnjem',
  'Gradišče pri Vipavi',
  'Gradišče pri Vojniku',
  'Gradišče v Tuhinju',
  'Gradišče-K. o. Grad. in Polj.',
  'Gradišica',
  'Gradiška',
  'Gradiške Laze',
  'Gradiški Dol',
  'Gradiško',
  'Gradnik',
  'Gradnje',
  'Gradno',
  'Grahovo',
  'Grahovo Brdo',
  'Grahovo ob Bači',
  'Grahovše',
  'Grajena',
  'Grajenščak',
  'Grajska vas',
  'Grant',
  'Graška Gora',
  'Grč Vrh',
  'Grčarevec',
  'Grčarice',
  'Grčarske Ravne',
  'Grče',
  'Grdina',
  'Grebenje',
  'Gregovce',
  'Grenc',
  'Gresovščak',
  'Grgar',
  'Grgarske Ravne',
  'Grgelj',
  'Griblje',
  'Grič',
  'Grič pri Dobličah',
  'Grič pri Klevevžu',
  'Grič pri Trebnjem',
  'Grinjan',
  'Grintovec',
  'Grintovec pri Osilnici',
  'Grivac',
  'Grivče',
  'Griže',
  'Grlava',
  'Grliče',
  'Grlinci',
  'Grm',
  'Grm pri Podzemlju',
  'Grmada',
  'Grmovlje',
  'Grobelce',
  'Grobelno - del',
  'Grobišče',
  'Groblje pri Prekopi',
  'Grosuplje',
  'Gruča',
  'Grudnica',
  'Grušce',
  'Grušena',
  'Gruškovec',
  'Grušova',
  'Grušovlje',
  'Gržeča vas',
  'Gubno',
  'Gumberk',
  'Gumnišče',
  'Gunte',
  'Hajdoše',
  'Hajndl',
  'Hajnsko',
  'Hardek',
  'Harije',
  'Harje',
  'Hercegovščak',
  'Herinja vas',
  'Hermanci',
  'Hinjce',
  'Hinje',
  'Hiteno',
  'Hlaponci',
  'Hlavče Njive',
  'Hlebce',
  'Hlebče',
  'Hleviše',
  'Hlevni Vrh',
  'Hlevnik',
  'Hmeljčič',
  'Hobovše pri Stari Oselici',
  'Hočevje',
  'Hočko Pohorje',
  'Hodoš',
  'Hohovica',
  'Hojče',
  'Hom',
  'Homec',
  'Horjul',
  'Hosta',
  'Hošnica',
  'Hotavlje',
  'Hotedršica',
  'Hotemaže',
  'Hotemež',
  'Hotična',
  'Hotinja vas',
  'Hotiza',
  'Hotovlja',
  'Hotunje',
  'Hramše',
  'Hranjigovci',
  'Hrast pri Jugorju',
  'Hrast pri Vinici',
  'Hrastek',
  'Hrastenice',
  'Hrastje',
  'Hrastje ob Bistrici',
  'Hrastje pri Cerkljah',
  'Hrastje pri Grosupljem',
  'Hrastje pri Mirni Peči',
  'Hrastje-Mota',
  'Hrastnik',
  'Hrastnik pri Trojanah',
  'Hrastno',
  'Hrastov Dol',
  'Hrastovec',
  'Hrastovec pod Bočem',
  'Hrastovec v Slov. goricah',
  'Hrastovica',
  'Hrastovlje',
  'Hrastulje',
  'Hrašče',
  'Hraše',
  'Hraše pri Preddvoru',
  'Hrašenski Vrh',
  'Hrenca',
  'Hrenova',
  'Hrenovice',
  'Hrib',
  'Hrib - Loški Potok',
  'Hrib nad Ribčami',
  'Hrib pri Cerovcu',
  'Hrib pri Fari',
  'Hrib pri Hinjah',
  'Hrib pri Kamniku',
  'Hrib pri Koprivniku',
  'Hrib pri Orehku',
  'Hribarjevo',
  'Hribi',
  'Hribljane',
  'Hrovača',
  'Hrpelje',
  'Hrustovo',
  'Hruševec',
  'Hruševica',
  'Hruševje',
  'Hruševka',
  'Hruševlje',
  'Hruševo',
  'Hrušica',
  'Hruškarje',
  'Hrušovje',
  'Hrvaški Brod',
  'Hrvatini',
  'Huda Jama',
  'Huda Polica',
  'Hudajužna',
  'Hude Ravne',
  'Hudeje',
  'Hudenje',
  'Hudi Graben',
  'Hudi Konec',
  'Hudi Kot',
  'Hudi Log',
  'Hudi Vrh',
  'Hudinja',
  'Hudo',
  'Hudo Brezje',
  'Hujbar',
  'Huje',
  'Hum',
  'Hum pri Ormožu',
  'Hušica',
  'Hvaletinci',
  'Idrija',
  'Idrija pri Bači',
  'Idrijska Bela',
  'Idrijske Krnice',
  'Idrijski Log',
  'Idrsko',
  'Idršek',
  'Ig',
  'Iga vas',
  'Iglenik',
  'Iglenik pri Veliki Loki',
  'Ihan',
  'Ihova',
  'Ilirska Bistrica',
  'Iljaševci',
  'Ilovca',
  'Ilovci',
  'Ilovka',
  'Imenje',
  'Imeno',
  'Imenska Gorca',
  'Imovica',
  'Irje',
  'Iška',
  'Iška Loka',
  'Iška vas',
  'Ivanci',
  'Ivančna Gorica',
  'Ivandol',
  'Ivanje selo',
  'Ivanji Grad',
  'Ivanjkovci',
  'Ivanjski Vrh',
  'Ivanjše',
  'Ivanjševci',
  'Ivanjševci ob Ščavnici',
  'Ivanjševski Vrh',
  'Ivanovci',
  'Ivenca',
  'Izgorje',
  'Izlake',
  'Izola',
  'Izvir',
  'Ižakovci',
  'Jablan',
  'Jablana',
  'Jablance',
  'Jablanica',
  'Jablaniške Laze',
  'Jablaniški Potok',
  'Jablovec',
  'Jagnjenica',
  'Jagoče',
  'Jagodje',
  'Jagodnik',
  'Jagršče',
  'Jakičevo',
  'Jakob pri Šentjurju',
  'Jakovce',
  'Jakovica',
  'Jakšiči',
  'Jama',
  'Jama pri Dvoru',
  'Jamna',
  'Jamnica',
  'Jamnik',
  'Janče',
  'Janeževo Brdo',
  'Janežovci',
  'Janežovski Vrh',
  'Janhova',
  'Jankova',
  'Jankoviči',
  'Janški Vrh',
  'Janškovo selo',
  'Janžev Vrh',
  'Janževa Gora',
  'Janževski Vrh',
  'Jarčja Dolina',
  'Jarčje Brdo',
  'Jarčji Vrh',
  'Jareninski Dol',
  'Jareninski Vrh',
  'Jarmovec',
  'Jarše',
  'Jasen',
  'Jastrebci',
  'Jastrebnik',
  'Javnik',
  'Javor',
  'Javorje',
  'Javorje pri Blagovici',
  'Javorje pri Gabrovki',
  'Javorjev Dol',
  'Javornik',
  'Javorniški Rovt',
  'Javorovica',
  'Jazbin Vrh',
  'Jazbina',
  'Jazbine',
  'Jazne',
  'Jedlovnik',
  'Jelarji',
  'Jelce',
  'Jelenče',
  'Jelendol',
  'Jelenik',
  'Jelenja vas',
  'Jelenk',
  'Jelenska Reber',
  'Jelični Vrh',
  'Jelovec',
  'Jelovec pri Makolah',
  'Jelovica',
  'Jelovice',
  'Jelovo',
  'Jelša',
  'Jelšane',
  'Jelše',
  'Jelše pri Otočcu',
  'Jelševec',
  'Jelševica',
  'Jelševnik',
  'Jeperjek',
  'Jeranovo',
  'Jerčin',
  'Jereka',
  'Jereslavec',
  'Jerinov Grič',
  'Jerman Vrh',
  'Jerneja vas',
  'Jeronim',
  'Jerovska vas',
  'Jeršanovo',
  'Jeršiče',
  'Jeruzalem',
  'Jesen',
  'Jesenica',
  'Jesenice',
  'Jesenje',
  'Jesenov Vrt',
  'Jesenovo',
  'Ješenca',
  'Ješovec',
  'Ješovec pri Kozjem',
  'Ješovec pri Šmarju',
  'Jevnica',
  'Jevšček',
  'Jezerca',
  'Jezerce pri Dobjem',
  'Jezerce pri Šmartnem',
  'Jezero',
  'Ježce',
  'Ježevec',
  'Ježni Vrh',
  'Jiršovci',
  'Jordankal',
  'Josipdol',
  'Jugorje',
  'Jugorje pri Metliki',
  'Junčje',
  'Jurišna vas',
  'Jurjevica',
  'Jurjevski Dol',
  'Jurka vas',
  'Jurklošter',
  'Jurna vas',
  'Jurovci',
  'Jurovski Dol',
  'Jurski Vrh',
  'Juršče',
  'Juršinci',
  'Juvanje',
  'Kačiče - Pared',
  'Kačji Dol',
  'Kačji Potok',
  'Kadrenci',
  'Kajžar',
  'Kal',
  'Kal - Koritnica',
  'Kal nad Kanalom',
  'Kal pri Dolah',
  'Kal pri Krmelju',
  'Kalce',
  'Kalce - Naklo',
  'Kale',
  'Kališe',
  'Kališovec',
  'Kalobje',
  'Kalše',
  'Kambreško',
  'Kamence',
  'Kamenče',
  'Kamenica',
  'Kamenik',
  'Kameno',
  'Kamenško',
  'Kamna Gora',
  'Kamna Gorca',
  'Kamna Gorica',
  'Kamni Potok',
  'Kamni Vrh',
  'Kamni Vrh pri Ambrusu',
  'Kamni Vrh pri Primskovem',
  'Kamnica',
  'Kamnik',
  'Kamnik pod Krimom',
  'Kamniška Bistrica',
  'Kamnje',
  'Kamno',
  'Kamno Brdo',
  'Kamovci',
  'Kampel',
  'Kanal',
  'Kanalski Lom',
  'Kanalski Vrh',
  'Kančevci',
  'Kandrše - del',
  'Kaniža',
  'Kanižarica',
  'Kanji Dol',
  'Kanjuce',
  'Kapca',
  'Kapele',
  'Kapelski Vrh',
  'Kapla',
  'Kaplanovo',
  'Kaplja vas',
  'Kapljišče',
  'Kaptol',
  'Karlče',
  'Karli',
  'Karlovica',
  'Kasaze',
  'Kastelec',
  'Katarija',
  'Kavče',
  'Kazlje',
  'Kebelj',
  'Kerinov Grm',
  'Kicar',
  'Kidričevo',
  'Kilovče',
  'Kisovec',
  'Kitni Vrh',
  'Klada',
  'Kladje',
  'Kladje nad Blanco',
  'Kladje pri Krmelju',
  'Kladnart',
  'Klake',
  'Klanc',
  'Klance',
  'Klanec',
  'Klanec pri Gabrovki',
  'Klanec pri Komnu',
  'Klanec pri Kozini',
  'Klavže',
  'Kleče pri Dolu',
  'Klečet',
  'Klek',
  'Klemenčevo',
  'Klenik',
  'Klenovik',
  'Klenovo',
  'Klinja vas',
  'Ključarovci pri Ljutomeru',
  'Ključevica',
  'Klokočovnik',
  'Klopce',
  'Klošter',
  'Knape',
  'Knej',
  'Kneške Ravne',
  'Knezdol',
  'Kneža',
  'Knežak',
  'Knežina',
  'Knežja Lipa',
  'Knežja Njiva',
  'Knežja vas',
  'Kobarid',
  'Kobdilj',
  'Kobile',
  'Kobilje',
  'Kobilščak',
  'Kobjeglava',
  'Koblarji',
  'Koble',
  'Koblek',
  'Koboli',
  'Kocjan',
  'Kočarija',
  'Kočarji',
  'Koče',
  'Kočevje',
  'Kočevska Reka',
  'Kočevske Poljane',
  'Kočice',
  'Kočki Vrh',
  'Kočna',
  'Kočno',
  'Kočno ob Ložnici',
  'Kočno pri Polskavi',
  'Kodreti',
  'Kog',
  'Koglo',
  'Kojsko',
  'Kokarje',
  'Kokolajnščak',
  'Kokoriči',
  'Kokošnje',
  'Kokra',
  'Kokrica',
  'Kolačno',
  'Kolenča vas',
  'Količevo',
  'Kolk',
  'Kolomban',
  'Kolovec',
  'Kolovrat',
  'Koludrje',
  'Komanija',
  'Komarna vas',
  'Komarnica',
  'Komen',
  'Komenda',
  'Komendska Dobrava',
  'Kompole',
  'Kompolje',
  'Konc',
  'Konca vas',
  'Konec',
  'Konj',
  'Konjiška vas',
  'Konjski Vrh',
  'Konjsko',
  'Konjšica - del',
  'Konuško',
  'Kopačnica',
  'Koper',
  'Kopivnik',
  'Kopriva',
  'Koprivna',
  'Koprivnica',
  'Koprivnik',
  'Koprivnik v Bohinju',
  'Koračice',
  'Korenitka',
  'Korenjak',
  'Koreno',
  'Koreno nad Horjulom',
  'Koretno',
  'Korita',
  'Korita na Krasu',
  'Koritnica',
  'Koritnice',
  'Koritno',
  'Koromači - Boškini',
  'Korošče',
  'Koroška Bela',
  'Koroška vas',
  'Koroška vas na Pohorju',
  'Koroški Selovec',
  'Korovci',
  'Korpe',
  'Korplje',
  'Korpule',
  'Korte',
  'Kortine',
  'Koseč',
  'Koseze',
  'Kosovelje',
  'Kostanj',
  'Kostanjek',
  'Kostanjevec',
  'Kostanjevica',
  'Kostanjevica na Krasu',
  'Kostanjevica na Krki',
  'Kostel',
  'Kostrevnica',
  'Kostrivnica',
  'Košarovci',
  'Koščake',
  'Košiše',
  'Koške Poljane',
  'Košnica',
  'Košnica pri Celju',
  'Koštabona',
  'Kot',
  'Kot na Pohorju',
  'Kot pri Damlju',
  'Kot pri Prevaljah',
  'Kot pri Rakitnici',
  'Kot pri Ribnici',
  'Kot pri Veliki Slevici',
  'Kotel',
  'Koti',
  'Kotlje',
  'Kotredež',
  'Kovača vas',
  'Kovačevci',
  'Kovačji Grad',
  'Kovaški Vrh',
  'Kovčice',
  'Kovk',
  'Kovor',
  'Kovski Vrh',
  'Kozana',
  'Kozarišče',
  'Kozarno',
  'Kozaršče',
  'Kozina',
  'Kozjak',
  'Kozjak nad Pesnico',
  'Kozjak pri Ceršaku',
  'Kozjane',
  'Kozje',
  'Kozji Vrh',
  'Kozji Vrh nad Dravogradom',
  'Kozloviči',
  'Kozmerice',
  'Kozminci',
  'Kožbana',
  'Kožljek',
  'Kožljevec',
  'Kožmani',
  'Kraberk',
  'Kračali',
  'Krajna',
  'Krajna Brda',
  'Krajna vas',
  'Krajnčica',
  'Krajno Brdo',
  'Kraljevci',
  'Kralji',
  'Kramarovci',
  'Kramplje',
  'Kranj',
  'Kranjska Gora',
  'Krapje',
  'Krasinec',
  'Krasna',
  'Krasno',
  'Krašce',
  'Krašči',
  'Kraška vas',
  'Krašnja',
  'Krašnji Vrh',
  'Krčevina',
  'Krčevina pri Vurbergu',
  'Kred',
  'Kregarjevo',
  'Kregolišče',
  'Kremberk',
  'Kremen',
  'Kremenca',
  'Kremenica',
  'Kremenik',
  'Kreplje',
  'Kresnica',
  'Kresnice',
  'Kresniške Poljane',
  'Kresniški Vrh',
  'Kristan vrh',
  'Kriška Reber',
  'Kriška vas',
  'Krištanci',
  'Krištandol',
  'Krivčevo',
  'Krivi Vrh',
  'Krivica',
  'Krivo Brdo',
  'Krivoglavice',
  'Križ',
  'Križan Vrh',
  'Križate',
  'Križe',
  'Križeča vas',
  'Križevci',
  'Križevci pri Ljutomeru',
  'Križevec',
  'Križevska vas',
  'Križišče',
  'Križmani',
  'Križna Gora',
  'Križni Vrh',
  'Krka',
  'Krkavče',
  'Krkovo nad Faro',
  'Krkovo pri Karlovici',
  'Krmačina',
  'Krmelj',
  'Krn',
  'Krnci',
  'Krnče',
  'Krnica',
  'Krnice',
  'Krnice pri Novakih',
  'Krog',
  'Kromberk',
  'Kropa',
  'Krplivnik',
  'Krsinji Vrh',
  'Krstenica',
  'Kršič',
  'Krška vas',
  'Krško',
  'Krtina',
  'Krtince',
  'Krtinovica',
  'Krupa',
  'Kruplivnik',
  'Krušče',
  'Krušni Vrh',
  'Krvava Peč',
  'Krvavčji Vrh',
  'Krvavi Potok',
  'Kržeti',
  'Kržišče',
  'Kržišče pri Čatežu',
  'Kubed',
  'Kuk',
  'Kukava',
  'Kukeč',
  'Kukenberk',
  'Kukmaka',
  'Kumen',
  'Kumpolje',
  'Kungota pri Ptuju',
  'Kunova',
  'Kunšperk',
  'Kupčinji Vrh',
  'Kupetinci',
  'Kupljenik',
  'Kupšinci',
  'Kuretno',
  'Kuršinci',
  'Kušernik',
  'Kuštanovci',
  'Kuteževo',
  'Kutinci',
  'Kuzarjev Kal',
  'Kuzma',
  'Kuželj',
  'Kuželjevec',
  'Kvasica',
  'Labinje',
  'Labor',
  'Lačaves',
  'Lačja vas',
  'Lačna Gora',
  'Ladja',
  'Ladra',
  'Lahomno',
  'Lahomšek',
  'Lahonci',
  'Lahov Graben',
  'Lahovče',
  'Lahovna',
  'Lahovo',
  'Lajše',
  'Lancova vas',
  'Lancovo',
  'Landek',
  'Landol',
  'Lanišče',
  'Laniše',
  'Laporje',
  'Laseno',
  'Lasigovci',
  'Lastnič',
  'Lastomerci',
  'Lašče',
  'Laše',
  'Laška vas',
  'Laška vas pri Štorah',
  'Laški Rovt',
  'Laško',
  'Latkova vas',
  'Lavrica',
  'Lavrovec',
  'Lavtarski Vrh',
  'Laze',
  'Laze nad Krko',
  'Laze pri Borovnici',
  'Laze pri Boštanju',
  'Laze pri Dolskem',
  'Laze pri Domžalah',
  'Laze pri Dramljah',
  'Laze pri Gobniku',
  'Laze pri Gorenjem Jezeru',
  'Laze pri Kostelu',
  'Laze pri Predgradu',
  'Laze pri Vačah',
  'Laze v Tuhinju',
  'Lazec',
  'Lazina',
  'Laziše',
  'Lazna',
  'Laznica',
  'Laže',
  'Lažiše',
  'Ledeča vas',
  'Ledina',
  'Ledine',
  'Ledinek',
  'Ledinica',
  'Ledinske Krnice',
  'Ledinsko Razpotje',
  'Legen',
  'Lehen na Pohorju',
  'Lekmarje',
  'Lemberg pri Novi Cerkvi',
  'Lemberg pri Šmarju',
  'Lemerje',
  'Lenart pri Gornjem Gradu',
  'Lenart v Slov. goricah',
  'Lendava',
  'Lendavske Gorice',
  'Lepa Njiva',
  'Lepena',
  'Lepence',
  'Lepi Vrh',
  'Lesce',
  'Lesično',
  'Leskovca',
  'Leskovec',
  'Leskovec pri Krškem',
  'Leskovec v Podborštu',
  'Leskovica',
  'Leskovica pri Šmartnem',
  'Lesno Brdo',
  'Lešane',
  'Leščevje',
  'Leše',
  'Lešje',
  'Lešnica',
  'Lešniški Vrh',
  'Lešnjake',
  'Letenice',
  'Letuš',
  'Levanjci',
  'Levec',
  'Levič',
  'Levpa',
  'Levstiki',
  'Libanja',
  'Libeliče',
  'Libeliška Gora',
  'Libelj',
  'Liberga',
  'Libna',
  'Liboje',
  'Libušnje',
  'Ličenca',
  'Lig',
  'Limbarska Gora',
  'Limbuš',
  'Limovce',
  'Lindek',
  'Lipa',
  'Lipa pri Frankolovem',
  'Lipce',
  'Lipe',
  'Lipica',
  'Lipje',
  'Liplje',
  'Lipni Dol',
  'Lipnica',
  'Lipnik',
  'Lipoglav',
  'Lipovci',
  'Lipovec',
  'Lipovec pri Kostelu',
  'Lipovec pri Škofji vasi',
  'Lipovšica',
  'Lipsenj',
  'Lisec',
  'Lisjaki',
  'Litija',
  'Litmerk',
  'Livek',
  'Livold',
  'Livške Ravne',
  'Ljubečna',
  'Ljubež v Lazih',
  'Ljubgojna',
  'Ljubično',
  'Ljubija',
  'Ljubinj',
  'Ljubljana',
  'Ljubnica',
  'Ljubno',
  'Ljubno ob Savinji',
  'Ljubstava',
  'Ljutomer',
  'Lobček',
  'Lobnica',
  'Loče',
  'Ločica ob Savinji',
  'Ločica pri Vranskem',
  'Ločič',
  'Ločki Vrh',
  'Log',
  'Log Čezsoški',
  'Log nad Škofjo Loko',
  'Log pod Mangartom',
  'Log pri Brezovici',
  'Log pri Mlinšah',
  'Log pri Polhovem Gradcu',
  'Log pri Vrhovem',
  'Log pri Žužemberku',
  'Log v Bohinju',
  'Logarji',
  'Logarovci',
  'Logarska Dolina',
  'Logaršče',
  'Logatec',
  'Logje',
  'Lohača',
  'Loje',
  'Loka',
  'Loka pri Dobrni',
  'Loka pri Framu',
  'Loka pri Mengšu',
  'Loka pri Zidanem Mostu',
  'Loka pri Žusmu',
  'Lokanja vas',
  'Lokarje',
  'Lokavci',
  'Lokavec',
  'Loke',
  'Loke pri Mozirju',
  'Loke pri Planini',
  'Loke pri Zagorju',
  'Loke v Tuhinju',
  'Lokev',
  'Lokovec',
  'Lokovica',
  'Lokovina',
  'Lokrovec',
  'Lokve',
  'Lokve pri Dobrniču',
  'Lokvica',
  'Lom',
  'Lom nad Volčo',
  'Lom pod Storžičem',
  'Lomanoše',
  'Lome',
  'Lomno',
  'Lončarjev Dol',
  'Lončarovci',
  'Lopaca',
  'Lopar',
  'Lopata',
  'Lopatnik',
  'Lopatnik pri Velenju',
  'Loperšice',
  'Lormanje',
  'Loška Gora',
  'Loška Gora pri Zrečah',
  'Loška vas',
  'Lovnik',
  'Lovranovo',
  'Lovrenc na Dravskem polju',
  'Lovrenc na Pohorju',
  'Lovsko Brdo',
  'Lozice',
  'Lož',
  'Ložane',
  'Lože',
  'Ložec',
  'Ložice',
  'Ložina',
  'Ložnica',
  'Ložnica pri Žalcu',
  'Lucija',
  'Lucova',
  'Lučarjev Kal',
  'Luče',
  'Lučine',
  'Ludranski Vrh',
  'Lukačevci',
  'Lukanja',
  'Lukavci',
  'Lukini',
  'Lukovec',
  'Lukovek',
  'Lukovica pri Brezovici',
  'Lukovica pri Domžalah',
  'Lunovec',
  'Lupinica',
  'Lušečka vas',
  'Lutrje',
  'Lutrško selo',
  'Lutverci',
  'Luža',
  'Lužarji',
  'Luže',
  'Mače',
  'Mačji Dol',
  'Mački',
  'Mačkovci',
  'Mačkovec',
  'Mačkovec pri Dvoru',
  'Mačkovec pri Suhorju',
  'Mačkovec pri Škocjanu',
  'Magolnik',
  'Magozd',
  'Mahneti',
  'Mahniči',
  'Mahovci',
  'Mahovnik',
  'Majcni',
  'Majski Vrh',
  'Majšperk',
  'Makole',
  'Makoše',
  'Mala Brda',
  'Mala Breza',
  'Mala Bukovica',
  'Mala Cikava',
  'Mala Dobrava',
  'Mala Dolina',
  'Mala Goba',
  'Mala Gora',
  'Mala Goričica',
  'Mala Hubajnica',
  'Mala Ilova Gora',
  'Mala Kostrevnica',
  'Mala Lahinja',
  'Mala Lašna',
  'Mala Ligojna',
  'Mala Loka',
  'Mala Loka pri Višnji Gori',
  'Mala Mislinja',
  'Mala Nedelja',
  'Mala Pirešica',
  'Mala Polana',
  'Mala Pristava',
  'Mala Račna',
  'Mala sela',
  'Mala Slevica',
  'Mala Stara vas',
  'Mala Strmica',
  'Mala Ševnica',
  'Mala Štanga',
  'Mala Varnica',
  'Mala vas',
  'Mala vas pri Grosupljem',
  'Mala vas pri Ormožu',
  'Malahorna',
  'Male Braslovče',
  'Male Brusnice',
  'Male Češnjice',
  'Male Dole',
  'Male Dole pri Stehanji vasi',
  'Male Dole pri Temenici',
  'Male Grahovše',
  'Male Kompolje',
  'Male Lašče',
  'Male Lese',
  'Male Lipljene',
  'Male Loče',
  'Male Pece',
  'Male Poljane',
  'Male Rebrce',
  'Male Rodne',
  'Male Vodenice',
  'Male Vrhe',
  'Male Žablje',
  'Malečnik',
  'Malence',
  'Malenska vas',
  'Malenski Vrh',
  'Mali Ban',
  'Mali Brebrovnik',
  'Mali Breg',
  'Mali Cerovec',
  'Mali Cirnik pri Šentjanžu',
  'Mali dol',
  'Mali Dol',
  'Mali Gaber',
  'Mali Hrib',
  'Mali Jelnik',
  'Mali Kal',
  'Mali Kamen',
  'Mali Konec',
  'Mali Koren',
  'Mali Korinj',
  'Mali Kum',
  'Mali Lipoglav',
  'Mali Lipovec',
  'Mali Ločnik',
  'Mali Log',
  'Mali Moravščak',
  'Mali Nerajec',
  'Mali Obrež',
  'Mali okič',
  'Mali Orehek',
  'Mali Osolnik',
  'Mali Otok',
  'Mali Podljuben',
  'Mali Podlog',
  'Mali Rakitovec',
  'Mali Rigelj',
  'Mali Slatnik',
  'Mali Trn',
  'Mali Videm',
  'Mali Vrh',
  'Mali Vrh pri Prežganju',
  'Mali Vrh pri Šmarju',
  'Malija',
  'Maline',
  'Maline pri Štrekljevcu',
  'Malinišče',
  'Malkovec',
  'Malna',
  'Malni',
  'Malo Črnelo',
  'Malo Globoko',
  'Malo Hudo',
  'Malo Lešče',
  'Malo Lipje',
  'Malo Mlačevo',
  'Malo Mraševo',
  'Malo Naklo',
  'Malo Polje',
  'Malo Tinje',
  'Malo Trebeljevo',
  'Malo Ubeljsko',
  'Malovše',
  'Mamolj',
  'Manče',
  'Manžan',
  'Marendol',
  'Marezige',
  'Maribor',
  'Marija Dobje',
  'Marija Gradec',
  'Marija Reka',
  'Marijina vas',
  'Marinča vas',
  'Marinčev Grič',
  'Marinčki',
  'Marindol',
  'Marjeta na Dravskem polju',
  'Markečica',
  'Markišavci',
  'Markovci',
  'Markovec',
  'Markovo',
  'Markovščina',
  'Marno',
  'Marolče',
  'Maršiči',
  'Martinj Vrh',
  'Martinja vas',
  'Martinja vas pri Mokronogu',
  'Martinjak',
  'Martinje',
  'Martjanci',
  'Masore',
  'Matavun',
  'Matena',
  'Matenja vas',
  'Materija',
  'Matjaševci',
  'Matke',
  'Mavčiče',
  'Mavrc',
  'Mavrlen',
  'Medana',
  'Medija',
  'Medlog',
  'Medno',
  'Medribnik',
  'Medvedce',
  'Medvedica',
  'Medvedje Brdo',
  'Medvedjek',
  'Medvode',
  'Meglenik',
  'Meja',
  'Meje',
  'Mekinje',
  'Mekinje nad Stično',
  'Mekotnjak',
  'Melanjski Vrh',
  'Mele',
  'Melinci',
  'Meliše',
  'Meljski Hrib',
  'Mengeš',
  'Meniška vas',
  'Merče',
  'Mereče',
  'Mestinje',
  'Mestni Vrh',
  'Metava',
  'Metlika',
  'Metnaj',
  'Metni Vrh',
  'Metulje',
  'Mevce',
  'Mevkuž',
  'Mezgovci',
  'Mezgovci ob Pesnici',
  'Mežica',
  'Migojnice',
  'Migolica',
  'Migolska Gora',
  'Mihalovci',
  'Mihalovec',
  'Mihelca',
  'Mihele',
  'Mihelja vas',
  'Mihovce',
  'Mihovci pri Vel. Nedelji',
  'Mihovec',
  'Mihovica',
  'Mihovo',
  'Miklavž na Dravskem polju',
  'Miklavž pri Ormožu',
  'Miklavž pri Taboru',
  'Mikote',
  'Milava',
  'Miliči',
  'Milje',
  'Miren',
  'Mirke',
  'Mirna',
  'Mirna Peč',
  'Mirna vas',
  'Mirtoviči',
  'Misliče',
  'Mislinja',
  'Mislinjska Dobrava',
  'Mišače',
  'Mišji Dol',
  'Mizni Dol',
  'Mlače',
  'Mladje',
  'Mlajtinci',
  'Mlaka',
  'Mlaka nad Lušo',
  'Mlaka pri Kočevju',
  'Mlaka pri Kočevski Reki',
  'Mlaka pri Kranju',
  'Mlake',
  'Mleščevo',
  'Mlinsko',
  'Mlinše',
  'Močila',
  'Močile',
  'Močilno',
  'Močle',
  'Močna',
  'Močvirje',
  'Modraže',
  'Modrej',
  'Modrejce',
  'Modrič',
  'Mohorje',
  'Mojstrana',
  'Mokronog',
  'Montinjan',
  'Morava',
  'Moravci v Slov. goricah',
  'Moravče',
  'Moravče pri Gabrovki',
  'Moravske Toplice',
  'Moravška Gora',
  'Morje',
  'Morsko',
  'Most',
  'Most na Soči',
  'Moste',
  'Mostec',
  'Mostečno',
  'Mostje',
  'Moščanci',
  'Moše',
  'Mošenik',
  'Moškanjci',
  'Moškrin',
  'Mošnje',
  'Mota',
  'Motnik',
  'Motovilci',
  'Motvarjevci',
  'Moverna vas',
  'Movraž',
  'Mozelj',
  'Mozirje',
  'Možjanca',
  'Mramorovo pri Lužarjih',
  'Mramorovo pri Pajkovem',
  'Mrčna sela',
  'Mrše',
  'Mršeča vas',
  'Mrtovec',
  'Mrtvice',
  'Mrzla Luža',
  'Mrzla Planina',
  'Mrzlava vas',
  'Mrzli Log',
  'Mrzli Vrh',
  'Mrzlo Polje',
  'Muhabran',
  'Mulhe',
  'Muljava',
  'Murave',
  'Muretinci',
  'Murska Sobota',
  'Murski Črnci',
  'Murski Petrovci',
  'Murski Vrh',
  'Murščak',
  'Muta',
  'Na Logu',
  'Nadanje selo',
  'Nadbišec',
  'Nadgrad',
  'Nadlesk',
  'Nadole',
  'Nadrožica',
  'Naklo',
  'Nanos',
  'Naraplje',
  'Naredi',
  'Narin',
  'Nasirec',
  'Nasova',
  'Nasovče',
  'Navrški Vrh',
  'Nazarje',
  'Neblo',
  'Nebova',
  'Nedelica',
  'Negastrn',
  'Negova',
  'Negovski Vrh',
  'Nemci',
  'Nemčavci',
  'Nemilje',
  'Nemška Gora',
  'Nemška Loka',
  'Nemška vas',
  'Nemška vas na Blokah',
  'Nemški Rovt',
  'Neradnovci',
  'Nestoplja vas',
  'Neverke',
  'Nevlje',
  'Nezbiše',
  'Nimno',
  'Nizka',
  'Niževec',
  'Njiverce',
  'Njivica',
  'Njivice',
  'Nomenj',
  'Norički Vrh',
  'Noršinci',
  'Noršinci pri Ljutomeru',
  'Noše',
  'Notranje Gorice',
  'Nova Cerkev',
  'Nova Gora',
  'Nova Gora nad Slov. Bistrico',
  'Nova Gorica',
  'Nova Lipa',
  'Nova Oselica',
  'Nova sela',
  'Nova Sušica',
  'Nova Štifta',
  'Nova vas',
  'Nova vas nad Dragonjo',
  'Nova vas ob Sotli',
  'Nova vas pri Jelšanah',
  'Nova vas pri Konjicah',
  'Nova vas pri Lescah',
  'Nova vas pri Markovcih',
  'Nova vas pri Mokricah',
  'Nova vas pri Šmarju',
  'Novake',
  'Nove Ložine',
  'Novelo',
  'Novi Grad',
  'Novi Kot',
  'Novi Lazi',
  'Novi Pot',
  'Novi Svet',
  'Novi vrh',
  'Novinci',
  'Novo Celje',
  'Novo mesto',
  'Novo Tepanje',
  'Novokračine',
  'Nozno',
  'Nožed',
  'Nožice',
  'Nunska Graba',
  'Nuskova',
  'Občice',
  'Občine',
  'Obla Gorica',
  'Obloke',
  'Obolno',
  'Obrat',
  'Obrež',
  'Obrežje',
  'Obrežje pri Zidanem Mostu',
  'Obrh',
  'Obrh pri Dragatušu',
  'Obrne',
  'Obrov',
  'Obrše',
  'Ocinje',
  'Ocizla',
  'Očeslavci',
  'Odranci',
  'Odrga',
  'Ogljenšak',
  'Ogorevc',
  'Ogulin',
  'Ohonica',
  'Ojstri Vrh',
  'Ojstrica',
  'Ojstriška vas',
  'Ojstro',
  'Okljuka',
  'Oklukova Gora',
  'Okonina',
  'Okoslavci',
  'Okoška Gora',
  'Okrog',
  'Okrog pri Motniku',
  'Okroglice',
  'Okroglo',
  'Olešče',
  'Olika',
  'Olimje',
  'Olševek',
  'Omota',
  'Onek',
  'Onkraj Meže',
  'Opale',
  'Opalkovo',
  'Opatje selo',
  'Oplotnica',
  'Orehek',
  'Orehek pri Materiji',
  'Orehova vas',
  'Orehovci',
  'Orehovec',
  'Orehovica',
  'Orehovlje',
  'Orehovo',
  'Orehovski Vrh',
  'Orešje',
  'Orešje na Bizeljskem',
  'Orešje nad Sevnico',
  'Orkljevec',
  'Orla vas',
  'Orlaka',
  'Orle',
  'Orlek',
  'Ormož',
  'Ornuška vas',
  'Orova vas',
  'Ortnek',
  'Ortnice',
  'Osek',
  'Osenca',
  'Osilnica',
  'Oskoršnica',
  'Oslica',
  'Osluševci',
  'Osojnica',
  'Osojnik',
  'Osolnik',
  'Osp',
  'Osrečje',
  'Osredek',
  'Osredek nad Stično',
  'Osredek pri Dobrovi',
  'Osredek pri Hubajnici',
  'Osredek pri Krmelju',
  'Osredek pri Podsredi',
  'Osredek pri Trški Gori',
  'Osredek pri Zrečah',
  'Osredke',
  'Ostenk',
  'Ostrog',
  'Ostrovica',
  'Ostrožnik',
  'Ostrožno Brdo',
  'Ostrožno pri Ločah',
  'Ostrožno pri Ponikvi - del',
  'Ošelj',
  'Oševek',
  'Oševljek',
  'Oštrc',
  'Otalež',
  'Otavice',
  'Otavnik',
  'Otemna',
  'Otiški Vrh',
  'Otlica',
  'Otoče',
  'Otočec',
  'Otok',
  'Otonica',
  'Otošče',
  'Otovci',
  'Otovec',
  'Ovsiše',
  'Ozeljan',
  'Ožbalt',
  'Pacinje',
  'Padeški Vrh',
  'Padež',
  'Padna',
  'Padovo pri Fari',
  'Padovo pri Osilnici',
  'Paha',
  'Paka',
  'Paka - del',
  'Paka pri Predgradu',
  'Paka pri Velenju',
  'Pako',
  'Palčje',
  'Paljevo',
  'Paloviče',
  'Pameče',
  'Pance',
  'Paneče',
  'Pangrč Grm',
  'Pangršica',
  'Panovci',
  'Papeži',
  'Papirnica',
  'Paradišče',
  'Paradiž',
  'Parecag',
  'Paričjak',
  'Paridol',
  'Parižlje',
  'Parje',
  'Parož',
  'Paška vas',
  'Paški Kozjak',
  'Paunoviči',
  'Pavičiči',
  'Pavla vas',
  'Pavlica',
  'Pavlova vas',
  'Pavlovci',
  'Pavlovski Vrh',
  'Pece',
  'Pecelj',
  'Peč',
  'Pečarovci',
  'Peče',
  'Pečica',
  'Pečice',
  'Pečine',
  'Pečje',
  'Pečke',
  'Pečki',
  'Pečnik',
  'Pečovje',
  'Pečovnik',
  'Pedrovo',
  'Pekel',
  'Pekre',
  'Penoje',
  'Pepelno',
  'Peračica',
  'Perati',
  'Perišče',
  'Pernica',
  'Pernice',
  'Perniki',
  'Pernovo',
  'Perovec',
  'Perovo',
  'Pertoča',
  'Perudina',
  'Pesje',
  'Peskovci',
  'Pesnica',
  'Pesnica pri Mariboru',
  'Pesniški Dvor',
  'Pestike',
  'Peščeni Vrh',
  'Peščenik',
  'Petane',
  'Petanjci',
  'Petelinje',
  'Petelinjek',
  'Petelinjek pri Ločah',
  'Petišovci',
  'Petkovec',
  'Petrina',
  'Petrinci',
  'Petrinje',
  'Petrova vas',
  'Petrovče',
  'Petrovo Brdo',
  'Petrušnja vas',
  'Pevno',
  'Pijana Gora',
  'Pijava Gorica',
  'Pijavice',
  'Pijovci',
  'Pikovnik',
  'Pilštanj',
  'Pince',
  'Pince - Marof',
  'Piran',
  'Pirče',
  'Pirešica',
  'Pirmane',
  'Piršenbreg',
  'Pirševo',
  'Pisari',
  'Pišece',
  'Pivka',
  'Pivola',
  'Placar',
  'Placerovci',
  'Plač',
  'Plače',
  'Planica',
  'Planina',
  'Planina na Pohorju',
  'Planina nad Horjulom',
  'Planina pod Golico',
  'Planina pod Šumikom',
  'Planina pri Cerknem',
  'Planina pri Raki',
  'Planina pri Sevnici',
  'Planina v Podbočju',
  'Planinca',
  'Planinska vas',
  'Planinski Vrh',
  'Planjsko',
  'Plat',
  'Platinovec',
  'Plave',
  'Plavje',
  'Plavški Rovt',
  'Plazovje',
  'Plemberk',
  'Ples',
  'Plesko',
  'Pleš',
  'Pleše',
  'Plešivec',
  'Plešivica',
  'Plešivica pri Žalni',
  'Plešivo',
  'Pleterje',
  'Pletovarje',
  'Plintovec',
  'Pliskovica',
  'Plitvica',
  'Plitvički Vrh',
  'Plodršnica',
  'Plosovo',
  'Pluska',
  'Plužna',
  'Plužnje',
  'Pobegi',
  'Pobrež',
  'Pobrežje',
  'Počakovo',
  'Poče',
  'Počehova',
  'Počenik',
  'Podbela',
  'Podbeže',
  'Podblica',
  'Podboč',
  'Podbočje',
  'Podboršt',
  'Podboršt pri Komendi',
  'Podbrdo',
  'Podbreg',
  'Podbrezje',
  'Podbreže',
  'Podbukovje',
  'Podbukovje pri Vačah',
  'Podcerkev',
  'Podčetrtek',
  'Poden',
  'Podgaj',
  'Podgora',
  'Podgora pri Dolskem',
  'Podgora pri Ložu',
  'Podgora pri Zlatem Polju',
  'Podgorci',
  'Podgorica',
  'Podgorica pri Pečah',
  'Podgorica pri Podtaboru',
  'Podgorica pri Šmarju',
  'Podgorje',
  'Podgorje ob Sevnični',
  'Podgorje pod Čerinom',
  'Podgorje pri Letušu',
  'Podgorje pri Pišecah',
  'Podgozd',
  'Podgračeno',
  'Podgrad',
  'Podgrad na Pohorju',
  'Podgrad pri Vremah',
  'Podgradje',
  'Podgraje',
  'Podgrič',
  'Podhojni Hrib',
  'Podhom',
  'Podhosta',
  'Podhruška',
  'Podigrac',
  'Podjelje',
  'Podjelovo Brdo',
  'Podjelše',
  'Podklanc',
  'Podklanec',
  'Podkočna',
  'Podkogelj',
  'Podkoren',
  'Podkraj',
  'Podkraj pri Mežici',
  'Podkraj pri Velenju',
  'Podkraj pri Zagorju',
  'Podkum',
  'Podlanišče',
  'Podlehnik',
  'Podlesje',
  'Podlešje',
  'Podlipa',
  'Podlipoglav',
  'Podlipovica',
  'Podlisec',
  'Podljubelj',
  'Podlog',
  'Podlog pod Bohorjem',
  'Podlog v Savinjski Dolini',
  'Podlom',
  'Podlonk',
  'Podlož',
  'Podlože',
  'Podmelec',
  'Podmilj',
  'Podmolnik',
  'Podnanos',
  'Podnart',
  'Podob',
  'Podobeno',
  'Podolnica',
  'Podolševa',
  'Podova',
  'Podpeca',
  'Podpeč',
  'Podpeč nad Marofom',
  'Podpeč ob Dravinji',
  'Podpeč pod Skalo',
  'Podpeč pri Šentvidu',
  'Podplanina',
  'Podplat',
  'Podpleče',
  'Podplešivica',
  'Podporezen',
  'Podpreska',
  'Podpulfrca',
  'Podraga',
  'Podreber',
  'Podreča',
  'Podrečje',
  'Podroje',
  'Podsabotin',
  'Podskrajnik',
  'Podslivnica',
  'Podsmrečje',
  'Podsmreka',
  'Podsmreka pri Velikih Laščah',
  'Podsmreka pri Višnji Gori',
  'Podsreda',
  'Podstene pri Kostelu',
  'Podstenice',
  'Podstenje',
  'Podstenjšek',
  'Podstran',
  'Podstrm',
  'Podstrmec',
  'Podstudenec',
  'Podšentjur',
  'Podtabor',
  'Podturn',
  'Podturn pri Dol. Toplicah',
  'Podulaka',
  'Podulce',
  'Podvelka',
  'Podveža',
  'Podvin',
  'Podvin pri Polzeli',
  'Podvinci',
  'Podvine',
  'Podvinje',
  'Podvolovljek',
  'Podvrh',
  'Podzemelj',
  'Podžaga',
  'Pogled',
  'Pogonik',
  'Pohorje',
  'Poklek nad Blanco',
  'Poklek pri Podsredi',
  'Pokojišče',
  'Pokojnica',
  'Pokoše',
  'Polajna',
  'Polana',
  'Polenci',
  'Polene',
  'Polenšak',
  'Poletiči',
  'Polhov Gradec',
  'Polhovica',
  'Polica',
  'Police',
  'Polička vas',
  'Polički Vrh',
  'Poljana',
  'Poljane',
  'Poljane nad Blagovico',
  'Poljane nad Škofjo Loko',
  'Poljane pri Mirni Peči',
  'Poljane pri Podgradu',
  'Poljane pri Primskovem',
  'Poljane pri Stični',
  'Poljane pri Štjaku',
  'Poljane pri Žužemberku',
  'Poljčane',
  'Poljče',
  'Polje',
  'Polje ob Sotli',
  'Polje pri Bistrici',
  'Polje pri Tržišču',
  'Polje pri Višnji Gori',
  'Polje pri Vodicah',
  'Poljšica pri Gorjah',
  'Poljšica pri Podnartu',
  'Poljubinj',
  'Polom',
  'Polšeče',
  'Polšina',
  'Polšnik',
  'Polzela',
  'Polzelo',
  'Polžanska Gorca',
  'Polžanska vas',
  'Polže',
  'Pomjan',
  'Pondor',
  'Pongrac',
  'Pongrce',
  'Ponikva',
  'Ponikva pri Žalcu',
  'Ponikve',
  'Ponikve pri Studencu',
  'Ponkvica',
  'Ponova vas',
  'Ponoviče',
  'Popetre',
  'Popovci',
  'Popovo',
  'Pordašinci',
  'Poreber',
  'Poreče',
  'Porezen',
  'Portorož',
  'Posavec',
  'Postaja',
  'Postojna',
  'Poštena vas',
  'Potarje',
  'Potiskavec',
  'Potoče',
  'Potok',
  'Potok pri Dornberku',
  'Potok pri Komendi',
  'Potok pri Muljavi',
  'Potok pri Vačah',
  'Potok v Črni',
  'Potoki',
  'Potoška vas',
  'Potov Vrh',
  'Povčeno',
  'Povir',
  'Povlje',
  'Povodje',
  'Površje',
  'Povžane',
  'Pozirno',
  'Poznanovci',
  'Poznikovo',
  'Požarje',
  'Požeg',
  'Poženik',
  'Požnica',
  'Prade',
  'Pragersko',
  'Prapetno',
  'Prapetno Brdo',
  'Prapreče',
  'Prapreče - del',
  'Prapreče pri Straži',
  'Prapreče pri Šentjerneju',
  'Prapretno',
  'Prapretno pri Hrastniku - del',
  'Praproče',
  'Praproče pri Grosupljem',
  'Praproče pri Temenici',
  'Praproče v Tuhinju',
  'Praproše',
  'Praprot',
  'Praprotna Polica',
  'Praprotnica',
  'Praprotno',
  'Praprotno Brdo',
  'Praše',
  'Prazniki',
  'Prebačevo',
  'Prebold',
  'Precetinci',
  'Preclava',
  'Prečna',
  'Predanovci',
  'Preddvor',
  'Predel',
  'Predenca',
  'Predgrad',
  'Predgriže',
  'Predjama',
  'Predloka',
  'Predmeja',
  'Predmost',
  'Predole',
  'Predoslje',
  'Predstruge',
  'Pregara',
  'Pregarje',
  'Prekopa',
  'Prekorje',
  'Prelasko',
  'Prelesje',
  'Prelog',
  'Preloge',
  'Preloge pri Konjicah',
  'Preloge pri Šmarju',
  'Preloka',
  'Prelože',
  'Prelože pri Lokvi',
  'Prelska',
  'Prem',
  'Premagovce',
  'Premančan',
  'Prepolje',
  'Prepuž',
  'Prerad',
  'Presečno',
  'Preserje',
  'Preserje pri Komnu',
  'Preserje pri Lukovici',
  'Preserje pri Radomljah',
  'Preserje pri Zlatem Polju',
  'Presika',
  'Preska',
  'Preska nad Kostrevnico',
  'Preska pri Dobrniču',
  'Presladol',
  'Prestranek',
  'Preša',
  'Preški Vrh',
  'Prešna Loka',
  'Prešnica',
  'Pretrež',
  'Pretrž',
  'Prevale',
  'Prevalje',
  'Prevalje pod Krimom',
  'Preveg',
  'Prevoje',
  'Prevoje pri Šentvidu',
  'Prevole',
  'Prezid',
  'Prezrenje',
  'Preženjske Njive',
  'Prežganje',
  'Prežigal',
  'Prhajevo',
  'Pri Cerkvi - Struge',
  'Pribinci',
  'Pribišje',
  'Prigorica',
  'Prihodi',
  'Prihova',
  'Prikrnica',
  'Prilesje',
  'Prilesje pri Plavah',
  'Prilipe',
  'Prilozje',
  'Primča vas',
  'Primostek',
  'Primož',
  'Primož pri Ljubnem',
  'Primož pri Šentjurju',
  'Primoži',
  'Primskovo',
  'Primštal',
  'Pristava',
  'Pristava nad Stično',
  'Pristava ob Krki',
  'Pristava pod Rako',
  'Pristava pri Lesičnem',
  'Pristava pri Leskovcu',
  'Pristava pri Mestinju',
  'Pristava pri Polh. Gradcu',
  'Pristava pri Šentjerneju',
  'Pristava pri Višnji Gori',
  'Pristavica',
  'Pristavica pri Vel. Gabru',
  'Pristavlja vas',
  'Pristavo',
  'Pristova',
  'Prnek',
  'Prosečka vas',
  'Proseniško',
  'Prosenjakovci',
  'Prožinska vas',
  'Pršetinci',
  'Prtovč',
  'Prušnja vas',
  'Prvačina',
  'Prvenci',
  'Prvine',
  'Pšajnovica',
  'Pšata',
  'Pšenična Polica',
  'Pševo',
  'Ptuj',
  'Ptujska Cesta',
  'Ptujska Gora',
  'Puconci',
  'Puče',
  'Pudob',
  'Pugled',
  'Pugled pri Karlovici',
  'Pugled pri Mokronogu',
  'Pungert',
  'Purga',
  'Purkače',
  'Pusti Gradec',
  'Pusti Hrib',
  'Pusti Javor',
  'Pustike',
  'Pusto Polje',
  'Pušča',
  'Puščava',
  'Pušče',
  'Pušenci',
  'Puštal',
  'Puževci',
  'Rača',
  'Rače',
  'Račeva',
  'Račica',
  'Račice',
  'Račja vas',
  'Račje selo',
  'Rački Vrh',
  'Račni Vrh',
  'Radana vas',
  'Radanja vas',
  'Radeče',
  'Radegunda',
  'Radehova',
  'Radelca',
  'Radenci',
  'Radenski Vrh',
  'Radež',
  'Radgonica',
  'Radizel',
  'Radkovec',
  'Radlek',
  'Radlje ob Dravi',
  'Radmirje',
  'Radmožanci',
  'Radna',
  'Radna vas',
  'Radoblje',
  'Radohova vas',
  'Radomerje',
  'Radomerščak',
  'Radomlje',
  'Radoslavci',
  'Radoši',
  'Radovci',
  'Radovica',
  'Radoviči',
  'Radovlja',
  'Radovljica',
  'Radovna',
  'Raduha',
  'Raduše',
  'Radvenci',
  'Rafolče',
  'Rajec',
  'Rajhenav',
  'Rajndol',
  'Rajnkovec',
  'Rajnovšče',
  'Rajšele',
  'Raka',
  'Rake',
  'Rakek',
  'Rakičan',
  'Rakitna',
  'Rakitnica',
  'Rakitnik',
  'Rakitovec',
  'Rakov Škocjan',
  'Rakova Steza',
  'Rakovci',
  'Rakovec',
  'Rakovica',
  'Rakovlje',
  'Rakovnik',
  'Rakovnik pri Birčni vasi',
  'Rakovnik pri Šentrupertu',
  'Rakulik',
  'Ranca',
  'Ranče',
  'Rankovci',
  'Rapljevo',
  'Raskovec',
  'Raša',
  'Rašica',
  'Ratanska vas',
  'Rateče',
  'Ratečevo Brdo',
  'Ratež',
  'Ratje',
  'Ratkovci',
  'Ravenska vas',
  'Ravna',
  'Ravnace',
  'Ravne',
  'Ravne na Blokah',
  'Ravne na Koroškem',
  'Ravne nad Šentrupertom',
  'Ravne pri Cerknem',
  'Ravne pri Mlinšah',
  'Ravne pri Šmartnem',
  'Ravne pri Zdolah',
  'Ravne pri Žireh',
  'Ravne v Bohinju',
  'Ravni',
  'Ravni Dol',
  'Ravnica',
  'Ravnik',
  'Ravnik pri Hotedršici',
  'Ravnje',
  'Ravno',
  'Ravno Brdo',
  'Razbor',
  'Razbor pri Čemšeniku',
  'Razborca',
  'Razbore',
  'Razbore-K. o. Ježni Vrh',
  'Razdelj',
  'Razdrto',
  'Razgor',
  'Razgor pri Žabljeku',
  'Razgorce',
  'Razguri',
  'Razkrižje',
  'Razori',
  'Razpotje',
  'Raztez',
  'Razvanje',
  'Rdeči Breg - del',
  'Rdeči Kal',
  'Reber',
  'Reber pri Škofljici',
  'Recenjak',
  'Rečica',
  'Rečica ob Paki',
  'Rečica ob Savinji',
  'Rejcov Grič',
  'Reka',
  'Remšnik',
  'Renče',
  'Renke',
  'Renkovci',
  'Rep',
  'Reparje',
  'Repče',
  'Repišče',
  'Replje',
  'Repnje',
  'Repno',
  'Repuš',
  'Resnik',
  'Reštanj',
  'Reteče',
  'Retje',
  'Retje nad Trbovljami',
  'Retnje',
  'Reva',
  'Ribče',
  'Ribčev Laz',
  'Ribjek',
  'Ribnica',
  'Ribnica na Pohorju',
  'Ribniško selo',
  'Ribno',
  'Rifengozd',
  'Rifnik',
  'Rigelj pri Ortneku',
  'Rigonce',
  'Riharjevec',
  'Rihpovec',
  'Rihtarovci',
  'Rimske Toplice',
  'Rinčetova Graba',
  'Ritmerk',
  'Ritomeče',
  'Ritoznoj',
  'Rižana',
  'Rjavci',
  'Rjavče',
  'Rjavica',
  'Rob',
  'Robanov Kot',
  'Robič',
  'Robidišče',
  'Robidni Breg',
  'Robidnica',
  'Roče',
  'Ročevnica',
  'Ročica',
  'Ročinj',
  'Rodež',
  'Rodica',
  'Rodik',
  'Rodine',
  'Rodine pri Trebnjem',
  'Rodmošci',
  'Rodni Vrh',
  'Rogačice',
  'Rogaška Slatina',
  'Rogašovci',
  'Rogatec',
  'Rogatec nad Želimljami',
  'Rogati Hrib',
  'Roginska Gorca',
  'Rogla',
  'Rogoza',
  'Rogoznica',
  'Roje',
  'Roje pri Čatežu',
  'Roje pri Trebelnem',
  'Ropoča',
  'Rosalnice',
  'Rošnja',
  'Rošpoh - del',
  'Rotman',
  'Rova',
  'Rove',
  'Rovišče',
  'Rovišče pri Studencu',
  'Rovt',
  'Rovt pod Menino',
  'Rovtarske Žibrše',
  'Rovte',
  'Rovte v Selški Dolini',
  'Rožanče',
  'Rožanec',
  'Rožar',
  'Roženberk',
  'Rožengrunt',
  'Roženpelj',
  'Rožice',
  'Rožič Vrh',
  'Rožički Vrh',
  'Rožično',
  'Rožna Dolina',
  'Rožni Dol',
  'Rožni Vrh',
  'Rožnik',
  'Rožno',
  'Rtiče',
  'Rubije',
  'Rucmanci',
  'Ručetna vas',
  'Rudna vas',
  'Rudnica',
  'Rudnik pri Moravčah',
  'Rudnik pri Radomljah',
  'Rudno',
  'Rudolfovo',
  'Ruhna vas',
  'Rumanja vas',
  'Runarsko',
  'Runeč',
  'Runtole',
  'Rupe',
  'Ruperče',
  'Ruše',
  'Rut',
  'Ruta',
  'Ržišče',
  'Ržiše',
  'Sabonje',
  'Sad',
  'Sadinja vas',
  'Sadinja vas pri Dvoru',
  'Sajenice',
  'Sajevce',
  'Sajevče',
  'Sajevec',
  'Saksid',
  'Sakušak',
  'Samotorica',
  'Sanabor',
  'Sapnik',
  'Sarsko',
  'Satahovci',
  'Sava',
  'Savci',
  'Savica',
  'Savina',
  'Savinsko',
  'Sebeborci',
  'Sebenje',
  'Seč',
  'Seča',
  'Sečje selo',
  'Sečovlje',
  'Sedlarjevo',
  'Sedlašek',
  'Sedlo',
  'Sedraž',
  'Segonje',
  'Segovci',
  'Sejanci',
  'Sejenice',
  'Sekirišče',
  'Sela',
  'Sela na Krasu',
  'Sela nad Podmelcem',
  'Sela pri Ajdovcu',
  'Sela pri Dobovi',
  'Sela pri Dobu',
  'Sela pri Dol. Toplicah',
  'Sela pri Dragatušu',
  'Sela pri Hinjah',
  'Sela pri Jugorju',
  'Sela pri Kamniku',
  'Sela pri Otovcu',
  'Sela pri Raki',
  'Sela pri Ratežu',
  'Sela pri Sobračah',
  'Sela pri Šentjerneju',
  'Sela pri Šmarju',
  'Sela pri Štravberku',
  'Sela pri Šumberku',
  'Sela pri Višnji Gori',
  'Sela pri Volčah',
  'Sela pri Vrčicah',
  'Sela pri Zajčjem Vrhu',
  'Sela pri Zburah',
  'Selca',
  'Selce',
  'Selce nad Blanco',
  'Selce pri Leskovcu',
  'Selce pri Moravčah',
  'Selce pri Špeharjih',
  'Sele',
  'Sele pri Polskavi',
  'Selišče',
  'Selišči',
  'Selnica ob Dravi',
  'Selnica ob Muri',
  'Selnik',
  'Selo',
  'Selo nad Laškim',
  'Selo nad Polhovim Gradcem',
  'Selo pri Bledu',
  'Selo pri Ihanu',
  'Selo pri Kostelu',
  'Selo pri Mirni',
  'Selo pri Moravčah',
  'Selo pri Pancah',
  'Selo pri Radohovi vasi',
  'Selo pri Robu',
  'Selo pri Vodicah',
  'Selo pri Vranskem',
  'Selo pri Zagorici',
  'Selo pri Zagorju',
  'Selo pri Žirovnici',
  'Selovec',
  'Selska Gora',
  'Selski Vrh',
  'Selšček',
  'Selšek',
  'Semič',
  'Senadole',
  'Senadolice',
  'Senčak',
  'Senčak pri Juršincih',
  'Senešci',
  'Seničica',
  'Senično',
  'Senik',
  'Seniški Breg',
  'Senovica',
  'Senovo',
  'Senožeče',
  'Senožete',
  'Senožeti',
  'Senuše',
  'Serdica',
  'Serjuče',
  'Sestrže',
  'Setnica - del',
  'Setnik',
  'Sevce',
  'Sevec',
  'Sevnica',
  'Sevno',
  'Sežana',
  'Sidol',
  'Sidraž',
  'Silova',
  'Silovec',
  'Sinja Gorica',
  'Sinji Vrh',
  'Sinovica',
  'Sirči',
  'Sitarovci',
  'Sitež',
  'Skadanščina',
  'Skakovci',
  'Skaručna',
  'Skoke',
  'Skomarje',
  'Skopo',
  'Skorba',
  'Skorišnjak',
  'Skorno',
  'Skorno pri Šoštanju',
  'Skrblje',
  'Skrilje',
  'Skrovnik',
  'Sladka Gora',
  'Sladki Vrh',
  'Slamna vas',
  'Slamniki',
  'Slamnjak',
  'Slance',
  'Slančji Vrh',
  'Slap',
  'Slap ob Idrijci',
  'Slape',
  'Slapnik',
  'Slaptinci',
  'Slatenik',
  'Slatina',
  'Slatina pri Dobjem',
  'Slatina pri Ponikvi',
  'Slatina v Rožni dolini',
  'Slatinski Dol',
  'Slatna',
  'Slatnik',
  'Slavče',
  'Slavina',
  'Slavinje',
  'Slavski Laz',
  'Slavšina',
  'Sleme',
  'Slepšek',
  'Slinovce',
  'Slivice',
  'Slivje',
  'Slivna',
  'Slivnica pri Celju',
  'Slivnica pri Mariboru',
  'Slivniško Pohorje',
  'Slivno',
  'Slogonsko',
  'Sloka Gora',
  'Slomi',
  'Slope',
  'Slovenj Gradec',
  'Slovenja vas',
  'Slovenska Bistrica',
  'Slovenska vas',
  'Slovenske Konjice',
  'Slovenski Javornik',
  'Slugovo',
  'Smast',
  'Smečice',
  'Smednik',
  'Smlednik',
  'Smokuč',
  'Smokvica',
  'Smoldno',
  'Smolenja vas',
  'Smoleva',
  'Smolinci',
  'Smolnik',
  'Smrečje',
  'Smrečje v Črni',
  'Smrečno',
  'Smrje',
  'Smrjene',
  'Smuka',
  'Snežatno',
  'Snežeče',
  'Snežnik',
  'Snovik',
  'Sobenja vas',
  'Sobetinci',
  'Sobrače',
  'Socerb',
  'Socka',
  'Soča',
  'Sočerga',
  'Sodevci',
  'Sodinci',
  'Sodišinci',
  'Sodji Vrh',
  'Sodna vas',
  'Sodražica',
  'Sojek',
  'Sokoliči',
  'Solčava',
  'Solkan',
  'Sopota',
  'Sopotnica',
  'Sora',
  'Sotensko pod Kalobjem',
  'Sotensko pri Šmarju',
  'Soteska',
  'Soteska pri Moravčah',
  'Sotina',
  'Soviče',
  'Sovinek',
  'Sovinja Peč',
  'Sovjak',
  'Sovodenj',
  'Sovra',
  'Soze',
  'Spodnja Bačkova',
  'Spodnja Bela',
  'Spodnja Besnica',
  'Spodnja Bilpa',
  'Spodnja Branica',
  'Spodnja Brežnica',
  'Spodnja Dobrava',
  'Spodnja Draga',
  'Spodnja Gorica',
  'Spodnja Hajdina',
  'Spodnja Idrija',
  'Spodnja Jablanica',
  'Spodnja Javoršica',
  'Spodnja Kanomlja',
  'Spodnja Kapla',
  'Spodnja Korena',
  'Spodnja Kostrivnica',
  'Spodnja Libna',
  'Spodnja Lipnica',
  'Spodnja Ložnica',
  'Spodnja Luša',
  'Spodnja Nova vas',
  'Spodnja Orlica',
  'Spodnja Pohanca',
  'Spodnja Polskava',
  'Spodnja Ponkvica',
  'Spodnja Pristava',
  'Spodnja Rečica',
  'Spodnja Ročica',
  'Spodnja Selnica',
  'Spodnja Senarska',
  'Spodnja Senica',
  'Spodnja Slivnica',
  'Spodnja Sorica',
  'Spodnja Sveča',
  'Spodnja Ščavnica',
  'Spodnja Velka',
  'Spodnja Vižinga',
  'Spodnja Voličina',
  'Spodnje Bitnje',
  'Spodnje Blato',
  'Spodnje Brezovo',
  'Spodnje Danje',
  'Spodnje Dobrenje',
  'Spodnje Dule',
  'Spodnje Duplice',
  'Spodnje Duplje',
  'Spodnje Gameljne',
  'Spodnje Gorče',
  'Spodnje Gorje',
  'Spodnje Gruškovje',
  'Spodnje Grušovje',
  'Spodnje Grušovlje',
  'Spodnje Hlapje',
  'Spodnje Hoče',
  'Spodnje Jablane',
  'Spodnje Jarše',
  'Spodnje Jelenje',
  'Spodnje Jezersko',
  'Spodnje Konjišče',
  'Spodnje Koseze',
  'Spodnje Kraše',
  'Spodnje Laze',
  'Spodnje Laže',
  'Spodnje Loke',
  'Spodnje Mestinje',
  'Spodnje Mladetiče',
  'Spodnje Negonje',
  'Spodnje Palovče',
  'Spodnje Partinje',
  'Spodnje Pijavško',
  'Spodnje Pirniče',
  'Spodnje Pobrežje',
  'Spodnje Poljčane',
  'Spodnje Prapreče',
  'Spodnje Prebukovje',
  'Spodnje Preloge',
  'Spodnje Roje',
  'Spodnje Sečovo',
  'Spodnje Selce',
  'Spodnje Slemene',
  'Spodnje Stranice',
  'Spodnje Stranje',
  'Spodnje Škofije',
  'Spodnje Tinsko',
  'Spodnje Verjane',
  'Spodnje Vetrno',
  'Spodnje Vodale',
  'Spodnje Vrtiče',
  'Spodnji Boč',
  'Spodnji Brnik',
  'Spodnji Dolič',
  'Spodnji Duplek',
  'Spodnji Gabernik',
  'Spodnji Gaj pri Pragerskem',
  'Spodnji Gasteraj',
  'Spodnji Hotič',
  'Spodnji Ivanjci',
  'Spodnji Jakobski Dol',
  'Spodnji Jernej',
  'Spodnji Kamenščak',
  'Spodnji Ključarovci',
  'Spodnji Kocjan',
  'Spodnji Leskovec',
  'Spodnji Log',
  'Spodnji Otok',
  'Spodnji Petelinjek',
  'Spodnji Porčič',
  'Spodnji Prekar',
  'Spodnji Razbor',
  'Spodnji Slemen',
  'Spodnji Stari Grad',
  'Spodnji Šemnik',
  'Spodnji Tuštanj',
  'Spodnji Velovlek',
  'Spodnji Vrsnik',
  'Spodnji Žerjavci',
  'Spuhlja',
  'Srakovlje',
  'Srebotje',
  'Srebrniče',
  'Srebrnik',
  'Središče',
  'Središče ob Dravi',
  'Srednik',
  'Srednja Bela',
  'Srednja Bistrica',
  'Srednja Dobrava',
  'Srednja Kanomlja',
  'Srednja vas',
  'Srednja vas - Goriče',
  'Srednja vas - Loški Potok',
  'Srednja vas - Poljane',
  'Srednja vas pri Dragi',
  'Srednja vas pri Kamniku',
  'Srednja vas pri Polh. Grad.',
  'Srednja vas pri Šenčurju',
  'Srednja vas v Bohinju',
  'Srednje',
  'Srednje Arto',
  'Srednje Bitnje',
  'Srednje Brdo',
  'Srednje Gameljne',
  'Srednje Grčevje',
  'Srednje Jarše',
  'Srednje Laknice',
  'Srednje Pijavško',
  'Srednji Dolič',
  'Srednji Gasteraj',
  'Srednji Globodol',
  'Srednji Lipovec',
  'Srednji Vrh',
  'Sremič',
  'Srgaši',
  'Srnjak',
  'Srobotnik ob Kolpi',
  'Srobotnik pri Vel. Laščah',
  'Sromlje',
  'Srpenica',
  'Srževica',
  'Stahovica',
  'Staje',
  'Stan',
  'Stanečka vas',
  'Stanetinci',
  'Stanežiče',
  'Staniše',
  'Stanjevci',
  'Stankovo',
  'Stanošina',
  'Stanovišče',
  'Stanovno',
  'Stanovsko',
  'Stara Bučka',
  'Stara Cerkev',
  'Stara Cesta',
  'Stara Fužina',
  'Stara Gora',
  'Stara Gora pri Šentilju',
  'Stara Gora pri Vel.Gabru',
  'Stara Lipa',
  'Stara Loka',
  'Stara Nova vas',
  'Stara Oselica',
  'Stara sela',
  'Stara Sušica',
  'Stara vas',
  'Stara vas - Bizeljsko',
  'Stara Vrhnika',
  'Stare Slemene',
  'Stare Žage',
  'Stari Breg',
  'Stari Dvor',
  'Stari Grad',
  'Stari Grad v Podbočju',
  'Stari Kot',
  'Stari log',
  'Stari Log',
  'Stari trg',
  'Stari trg ob Kolpi',
  'Stari trg pri Ložu',
  'Starihov Vrh',
  'Staro Brezje',
  'Staro selo',
  'Starod',
  'Starošince',
  'Starše',
  'Stavča vas',
  'Stavešinci',
  'Stavešinski Vrh',
  'Stebljevek',
  'Stegne',
  'Stehanja vas',
  'Stenica',
  'Stepani',
  'Steske',
  'Stična',
  'Stirpnik',
  'Stiška vas',
  'Stogovci',
  'Stojanski Vrh',
  'Stojnci',
  'Stolnik',
  'Stolovnik',
  'Stomaž',
  'Stopce',
  'Stopče',
  'Stope',
  'Stoperce',
  'Stopiče',
  'Stopnik',
  'Stopno',
  'Strahinj',
  'Strahomer',
  'Strahovlje',
  'Strajna',
  'Strane',
  'Stranice',
  'Stranje',
  'Stranje pri Dobrniču',
  'Stranje pri Škocjanu',
  'Stranje pri Velikem Gabru',
  'Stranska vas',
  'Stranska vas ob Višnjici',
  'Stranska vas pri Semiču',
  'Stranske Makole',
  'Stranski Vrh',
  'Straška Gorca',
  'Straža',
  'Straža na Gori',
  'Straža pri Dolu',
  'Straža pri Krškem',
  'Straža pri Moravčah',
  'Straža pri Novi Cerkvi',
  'Straža pri Oplotnici',
  'Straža pri Raki',
  'Straže',
  'Stražgonjca',
  'Stražica',
  'Stražišče',
  'Stražnji Vrh',
  'Strehovci',
  'Strejaci',
  'Strelac',
  'Strelci',
  'Strensko',
  'Strezetina',
  'Strjanci',
  'Strletje',
  'Strmca',
  'Strmec',
  'Strmec na Predelu',
  'Strmec nad Dobrno',
  'Strmec pri Destrniku',
  'Strmec pri Leskovcu',
  'Strmec pri Ormožu',
  'Strmec pri Polenšaku',
  'Strmec pri sv. Florijanu',
  'Strmica',
  'Strmo Rebro',
  'Strnišče',
  'Stročja vas',
  'Strojiči',
  'Strojna',
  'Strtenica',
  'Strtenik',
  'Strug',
  'Strukovci',
  'Strunjan',
  'Stružnica',
  'Stržišče',
  'Studena Gora',
  'Studenca',
  'Studence',
  'Studenčice',
  'Studenec',
  'Studenec na Blokah',
  'Studenec pri Krtini',
  'Studenice',
  'Studeno',
  'Studeno na Blokah',
  'Studor',
  'Studor v Bohinju',
  'Suha',
  'Suha pri Predosljah',
  'Suhadol',
  'Suhadole',
  'Suhi Vrh',
  'Suho',
  'Suhor',
  'Suhor pri Dol. Toplicah',
  'Suhorje',
  'Suša',
  'Sušak',
  'Sušica',
  'Sušje',
  'Sužid',
  'Sv. Ana v Slov. Goricah',
  'Sv. Andrej',
  'Sv. Anton',
  'Sv. Anton na Pohorju',
  'Sv. Barbara',
  'Sv. Boštjan',
  'Sv. Danijel',
  'Sv. Duh',
  'Sv. Duh na Ostrem vrhu',
  'Sv. Ema',
  'Sv. Florijan',
  'Sv. Gregor',
  'Sv. Jernej nad Muto',
  'Sv. Jurij',
  'Sv. Lenart',
  'Sv. Lovrenc',
  'Sv. Ožbolt',
  'Sv. Peter',
  'Sv. Petra Hrib',
  'Sv. Primož na Pohorju',
  'Sv. Primož nad Muto',
  'Sv. Tomaž',
  'Sv. Trije Kralji',
  'Sv. Trije Kralji v Slov. Gor.',
  'Sv. Trojica',
  'Sv. Trojica v Slov. goricah',
  'Sv. Vid',
  'Sv. Vrh',
  'Svečane',
  'Svečina',
  'Sveta Ana pri Ložu',
  'Sveta Gora',
  'Sveta Planina',
  'Sveta Trojica',
  'Svetelka',
  'Sveti Andrej',
  'Sveti Duh',
  'Sveti Florijan nad Škofjo Loko',
  'Sveti Jernej',
  'Sveti Jurij',
  'Sveti Jurij ob Ščavnici',
  'Sveti Lenart',
  'Sveti Štefan',
  'Sveti Tomaž',
  'Sveti Vid',
  'Svetina',
  'Svetinci',
  'Svetinja',
  'Svetinje',
  'Svetli Dol',
  'Sveto',
  'Svibnik',
  'Svibno',
  'Svinjsko',
  'Svino',
  'Svržaki',
  'Šafarsko',
  'Šahovec',
  'Šalamenci',
  'Šalara',
  'Šalinci',
  'Šalka vas',
  'Šalovci',
  'Šardinje',
  'Šared',
  'Šavna Peč',
  'Ščit',
  'Ščurki',
  'Šebrelje',
  'Šedem',
  'Šedina',
  'Šegova vas',
  'Šeki',
  'Šembije',
  'Šemnik',
  'Šempas',
  'Šempeter pri Gorici',
  'Šempeter v Savinj. Dolini',
  'Šenbric',
  'Šenčur',
  'Šentanel',
  'Šentgotard',
  'Šentilj pod Turjakom',
  'Šentilj v Slov. goricah',
  'Šentjakob',
  'Šentjanž',
  'Šentjanž nad Dravčami',
  'Šentjanž nad Štorami',
  'Šentjanž pri Dravogradu',
  'Šentjernej',
  'Šentjošt',
  'Šentjošt nad Horjulom',
  'Šentjungert',
  'Šentjur',
  'Šentjur na Polju',
  'Šentjurij na Dolenjskem',
  'Šentjurje',
  'Šentlambert',
  'Šentlovrenc',
  'Šentovec',
  'Šentožbolt',
  'Šentpavel',
  'Šentpavel na Dolenjskem',
  'Šentpavel pri Domžalah',
  'Šentrupert',
  'Šenturška Gora',
  'Šentvid pri Grobelnem',
  'Šentvid pri Lukovici',
  'Šentvid pri Planini',
  'Šentvid pri Stični',
  'Šentvid pri Zavodnju',
  'Šentviška Gora',
  'Šepulje',
  'Šerovo',
  'Šestdobe',
  'Šešče pri Preboldu',
  'Šetarova',
  'Ševlje',
  'Ševnica',
  'Šibelji',
  'Šibenik',
  'Šikole',
  'Šilentabor',
  'Šinkov Turn',
  'Šipek',
  'Širje',
  'Širmanski Hrib',
  'Široka Set',
  'Škalce',
  'Škale',
  'Škalske Cirkovce',
  'Škamevec',
  'Škarnice',
  'Škedenj',
  'Škemljevec',
  'Šklendrovec',
  'Škocjan',
  'Škofce',
  'Škofi',
  'Škofija',
  'Škofja Loka',
  'Škofja Riža',
  'Škofja vas',
  'Škoflje',
  'Škofljica',
  'Škovec',
  'Škrabče',
  'Škrajnek',
  'Škrbina',
  'Škrilje',
  'Škrjanče',
  'Škrjanče pri Novem mestu',
  'Škrjančevo',
  'Škrljevo',
  'Škrlovica',
  'Škufče',
  'Šlovrenc',
  'Šmalčja vas',
  'Šmarata',
  'Šmarca',
  'Šmarčna',
  'Šmarje',
  'Šmarje - Sap',
  'Šmarje pri Jelšah',
  'Šmarje pri Sežani',
  'Šmarješke Toplice',
  'Šmarjeta',
  'Šmarjeta pri Celju',
  'Šmartinske Cirkovce',
  'Šmartno',
  'Šmartno na Pohorju',
  'Šmartno ob Dreti',
  'Šmartno ob Paki',
  'Šmartno pri Litiji',
  'Šmartno pri Slovenj Gradcu',
  'Šmartno v Rožni dolini',
  'Šmartno v Tuhinju',
  'Šmatevž',
  'Šmaver',
  'Šmihel',
  'Šmihel nad Mozirjem',
  'Šmihel pod Nanosom',
  'Šmihel pri Žužemberku',
  'Šmiklavž',
  'Šmiklavž pri Škofji vasi',
  'Šmohor',
  'Šober',
  'Šomat',
  'Šoštanj',
  'Špeharji',
  'Špičnik',
  'Špital',
  'Špitalič',
  'Špitalič pri Slov. Konjicah',
  'Šprinc',
  'Šratovci',
  'Št. Janž pri Radljah',
  'Št. Jurij',
  'Štajer',
  'Štajerska vas',
  'Štajngrob',
  'Štajngrova',
  'Štalcerji',
  'Štangarske Poljane',
  'Štanjel',
  'Štatenberg',
  'Štatenberk',
  'Štefan pri Trebnjem',
  'Štefanja Gora',
  'Štjak',
  'Štore',
  'Štorje',
  'Štorovo',
  'Štravberk',
  'Štrekljevec',
  'Štrihovec',
  'Štrit',
  'Štrukljeva vas',
  'Šturmovci',
  'Šujica',
  'Šulinci',
  'Šumnik',
  'Šutna',
  'Tabor',
  'Tajhte',
  'Talčji Vrh',
  'Tanča Gora',
  'Tatinec',
  'Tatre',
  'Tavžlje',
  'Teharje',
  'Tehovec',
  'Tekačevo',
  'Telče',
  'Telčice',
  'Temenica',
  'Temljine',
  'Temnica',
  'Tenetiše',
  'Tepanje',
  'Tepanjski Vrh',
  'Tepe',
  'Ter',
  'Terbegovci',
  'Tešanovci',
  'Tešova',
  'Tevče',
  'Tibolci',
  'Tihaboj',
  'Tinjan',
  'Tinjska Gora',
  'Tirna',
  'Tisovec',
  'Tišenpolj',
  'Tišina',
  'Tlaka',
  'Tlake',
  'Todraž',
  'Tolčane',
  'Tolmin',
  'Tolminske Ravne',
  'Tolminski Lom',
  'Tolsti Vrh',
  'Tolsti Vrh p. R. na K. - del',
  'Tolsti Vrh p. R. Na K. - del',
  'Tolsti Vrh pri Mislinji',
  'Tomačevica',
  'Tomaj',
  'Tomaška vas',
  'Tomaž nad Vojnikom',
  'Tomažini',
  'Tomažja vas',
  'Tominje',
  'Tomišelj',
  'Topla',
  'Topol',
  'Topol pri Begunjah',
  'Topol pri Medvodah',
  'Topolc',
  'Topole',
  'Topolje',
  'Topolovci',
  'Topolovec',
  'Topolovo',
  'Topolšica',
  'Topovlje',
  'Torka',
  'Torovo',
  'Toško Čelo',
  'Tovsto',
  'Trata',
  'Trata pri Velesovem',
  'Trate',
  'Tratna ob Voglajni',
  'Tratna pri Grobelnem',
  'Trava',
  'Travna Gora',
  'Travni Dol',
  'Travnik',
  'Trbinc',
  'Trboje',
  'Trbonje',
  'Trbovlje',
  'Trčkov Grič',
  'Trčova',
  'Trdkova',
  'Trdobojci',
  'Trebanjski Vrh',
  'Trebča vas',
  'Trebče',
  'Trebelno',
  'Trebelno pri Palovčah',
  'Trebenče',
  'Trebeše',
  'Trebež',
  'Trebija',
  'Trebižani',
  'Trebnja Gorica',
  'Trebnje',
  'Trebnji Vrh',
  'Tremerje',
  'Trenta',
  'Trgovišče',
  'Triban',
  'Tribej',
  'Tribuče',
  'Trimlini',
  'Trlično',
  'Trnava',
  'Trniče',
  'Trnjava',
  'Trnje',
  'Trno',
  'Trnov Hrib',
  'Trnovci',
  'Trnovče',
  'Trnovec',
  'Trnovec pri Dramljah',
  'Trnovec pri Slovenski Bistrici',
  'Trnovica',
  'Trnovlje pri Celju',
  'Trnovlje pri Socki',
  'Trnovo',
  'Trnovo ob Soči',
  'Trnovska vas',
  'Trnovski Vrh',
  'Trobelno',
  'Troblje',
  'Trobni Dol',
  'Trojane',
  'Trojno',
  'Tropovci',
  'Troščine',
  'Trotkova',
  'Trpčane',
  'Trsek',
  'Trstenik',
  'Trščina',
  'Trška Gora',
  'Trška Gorca',
  'Trtnik',
  'Truške',
  'Trzin',
  'Tržec',
  'Tržič',
  'Tržišče',
  'Tublje pri Hrpeljah',
  'Tublje pri Komnu',
  'Tučna',
  'Tuji Grm',
  'Tuljaki',
  'Tuncovec',
  'Tunjice',
  'Tunjiška Mlaka',
  'Tupaliče',
  'Tupelče',
  'Turiška vas',
  'Turiška vas na Pohorju',
  'Turjak',
  'Turjanci',
  'Turjanski Vrh',
  'Turje',
  'Turnišče',
  'Turno',
  'Turnše',
  'Turški Vrh',
  'Tušev Dol',
  'Učak',
  'Učakovci',
  'Udje',
  'Udmat',
  'Ugovec',
  'Ukanc',
  'Ukanje',
  'Ulaka',
  'Unec',
  'Unično',
  'Uniše',
  'Urh',
  'Uršlja Gora',
  'Uršna sela',
  'Ustje',
  'Utik',
  'Utovlje',
  'Uzmani',
  'V Zideh',
  'Vače',
  'Vadarci',
  'Vadiče',
  'Vajgen',
  'Valburga',
  'Vale',
  'Valična vas',
  'Valterski Vrh',
  'Vanča vas',
  'Vaneča',
  'Vanetina',
  'Vanganel',
  'Varda',
  'Vareja',
  'Vareje',
  'Varoš',
  'Varpolje',
  'Vas',
  'Vaseno',
  'Vašca',
  'Vaše',
  'Vatovlje',
  'Vavpča vas pri Dobrniču',
  'Vavta vas',
  'Večeslavci',
  'Večje Brdo',
  'Večkoti',
  'Vedrijan',
  'Vejice',
  'Velenje',
  'Velesovo',
  'Veličane',
  'Velika Brda',
  'Velika Bukovica',
  'Velika Dobrava',
  'Velika Dolina',
  'Velika Goba',
  'Velika Hubajnica',
  'Velika Ilova Gora',
  'Velika Kostrevnica',
  'Velika Lahinja',
  'Velika Lašna',
  'Velika Ligojna',
  'Velika Loka',
  'Velika Nedelja',
  'Velika Pirešica',
  'Velika Planina',
  'Velika Polana',
  'Velika Preska',
  'Velika Pristava',
  'Velika Račna',
  'Velika Raven',
  'Velika sela',
  'Velika Slevica',
  'Velika Stara vas',
  'Velika Strmica',
  'Velika Ševnica',
  'Velika Štanga',
  'Velika Varnica',
  'Velika vas',
  'Velika vas pri Krškem',
  'Velike Bloke',
  'Velike Brusnice',
  'Velike Češnjice',
  'Velike Dole',
  'Velike Dole pri Temenici',
  'Velike Gorelce',
  'Velike Grahovše',
  'Velike Kompolje',
  'Velike Lašče',
  'Velike Lese',
  'Velike Lipljene',
  'Velike Loče',
  'Velike Malence',
  'Velike Pece',
  'Velike Poljane',
  'Velike Rebrce',
  'Velike Rodne',
  'Velike Vodenice',
  'Velike Vrhe',
  'Velike Žablje',
  'Veliki Ban',
  'Veliki Boč',
  'Veliki Brebrovnik',
  'Veliki Cerovec',
  'Veliki Cirnik',
  'Veliki Dol',
  'Veliki Gaber',
  'Veliki Hrib',
  'Veliki Jelnik',
  'Veliki Kal',
  'Veliki Kamen',
  'Veliki Korinj',
  'Veliki Lipoglav',
  'Veliki Lipovec',
  'Veliki Ločnik',
  'Veliki Nerajec',
  'Veliki Obrež',
  'Veliki Okič',
  'Veliki Orehek',
  'Veliki Osolnik',
  'Veliki Otok',
  'Veliki Podljuben',
  'Veliki Podlog',
  'Veliki Rakitovec',
  'Veliki Rigelj',
  'Veliki Slatnik',
  'Veliki Trn',
  'Veliki Videm',
  'Veliki Vrh',
  'Veliki Vrh pri Litiji',
  'Veliki Vrh pri Šmarju',
  'Veliko Brdo',
  'Veliko Črnelo',
  'Veliko Globoko',
  'Veliko Lipje',
  'Veliko Mlačevo',
  'Veliko Mraševo',
  'Veliko Polje',
  'Veliko Širje',
  'Veliko Tinje',
  'Veliko Trebeljevo',
  'Veliko Ubeljsko',
  'Velka',
  'Veniše',
  'Verače',
  'Verd',
  'Verdun',
  'Verdun pri Uršnih Selih',
  'Verje',
  'Vernek',
  'Verpete',
  'Veržej',
  'Vesca',
  'Vesela Gora',
  'Veščica',
  'Vešenik',
  'Vešter',
  'Vetrnik',
  'Vezovje',
  'Vič',
  'Vičanci',
  'Vidanovci',
  'Videm',
  'Videm pri Lukovici',
  'Videm pri Ptuju',
  'Videm pri Temenici',
  'Videž',
  'Vidonci',
  'Vidošiči',
  'Vidovica',
  'Vidrga',
  'Vihre',
  'Vikrče',
  'Vimolj',
  'Vimolj pri Predgradu',
  'Vinarje',
  'Vincarje',
  'Vine',
  'Vinec',
  'Vinharje',
  'Vinica',
  'Vinica pri Šmarjeti',
  'Vinice',
  'Vinička vas',
  'Vinja vas',
  'Vinje',
  'Vinje pri Moravčah',
  'Vinji Vrh',
  'Vinji Vrh pri Semiču',
  'Vinkov Vrh',
  'Vino',
  'Vinska Gora',
  'Vinska Gorica',
  'Vinski Vrh',
  'Vinski Vrh pri Šmarju',
  'Vintarjevec',
  'Vintarji',
  'Vintarovci',
  'Vipava',
  'Vipavski Križ',
  'Vipolže',
  'Vir',
  'Vir pri Nevljah',
  'Vir pri Stični',
  'Virlog',
  'Virmaše',
  'Virštanj',
  'Visejec',
  'Visoče',
  'Visoko',
  'Visoko pri Poljanah',
  'Visole',
  'Višelnica',
  'Viševca',
  'Viševek',
  'Višnja Gora',
  'Višnja vas',
  'Višnje',
  'Višnjevik',
  'Višnji Grm',
  'Vitan',
  'Vitanje',
  'Vitanjsko Skomarje',
  'Vitna vas',
  'Vitomarci',
  'Vitovlje',
  'Vizore',
  'Vnajnarje',
  'Vnanje Gorice',
  'Vodenovo',
  'Vodice',
  'Vodice nad Kamnikom',
  'Vodice pri Gabrovki',
  'Vodice pri Kalobju',
  'Vodice pri Slivnici',
  'Vodiško',
  'Vodole',
  'Vodranci',
  'Vodriž',
  'Vodruž',
  'Voduce',
  'Vodule',
  'Voglajna',
  'Voglarji',
  'Voglje',
  'Vogričevci',
  'Vogrsko',
  'Vojna vas',
  'Vojnik',
  'Vojsko',
  'Vojščica',
  'Voklo',
  'Volaka',
  'Volarje',
  'Volavlje',
  'Volča',
  'Volčanski Ruti',
  'Volče',
  'Volčja Draga',
  'Volčja Jama',
  'Volčje',
  'Volčje Njive',
  'Volčji Grad',
  'Volčji Potok',
  'Volčkova vas',
  'Volog',
  'Vologa',
  'Volovnik',
  'Vonarje',
  'Vopovlje',
  'Vosek',
  'Vošce',
  'Vošče',
  'Vovše',
  'Vrabče',
  'Vranja Peč',
  'Vranje',
  'Vranji Vrh',
  'Vranke',
  'Vranoviči',
  'Vransko',
  'Vrata',
  'Vratja vas',
  'Vratji Vrh',
  'Vratno',
  'Vrba',
  'Vrbica',
  'Vrbičje',
  'Vrbina',
  'Vrbje',
  'Vrbljene',
  'Vrbnje',
  'Vrbno',
  'Vrbovce',
  'Vrbovec',
  'Vrbovo',
  'Vrčice',
  'Vremski Britof',
  'Vrenska Gorca',
  'Vrh',
  'Vrh nad Krašnjo',
  'Vrh nad Laškim',
  'Vrh nad Želimljami',
  'Vrh pri Boštanju',
  'Vrh pri Dolskem',
  'Vrh pri Fari',
  'Vrh pri Hinjah',
  'Vrh pri Križu',
  'Vrh pri Ljubnu',
  'Vrh pri Mlinšah',
  'Vrh pri Pahi',
  'Vrh pri Poljanah',
  'Vrh pri Površju',
  'Vrh pri Sobračah',
  'Vrh pri Šentjerneju',
  'Vrh pri Trebelnem',
  'Vrh pri Višnji Gori',
  'Vrh Sv. Treh Kraljev',
  'Vrhe',
  'Vrhe - del',
  'Vrhek',
  'Vrhje',
  'Vrhloga',
  'Vrhnika',
  'Vrhnika pri Ložu',
  'Vrhole pri Laporju',
  'Vrhole pri Slov. Konjicah',
  'Vrhov Dol',
  'Vrhovci',
  'Vrhovje',
  'Vrhovlje',
  'Vrhovlje pri Kojskem',
  'Vrhovlje pri Kožbani',
  'Vrhovo',
  'Vrhovo pri Mirni Peči',
  'Vrhovo pri Šentlovrencu',
  'Vrhovo pri Žužemberku',
  'Vrhovska vas',
  'Vrhpeč',
  'Vrhpolje',
  'Vrhpolje pri Kamniku',
  'Vrhpolje pri Moravčah',
  'Vrhpolje pri Šentvidu',
  'Vrhtrebnje',
  'Vrhulje',
  'Vrsno',
  'Vršna vas',
  'Vršnik',
  'Vrt',
  'Vrtača',
  'Vrtače',
  'Vrtoče',
  'Vrtojba',
  'Vrtovče',
  'Vrtovin',
  'Vrzdenec',
  'Vučja Gomila',
  'Vučja vas',
  'Vuhred',
  'Vukovci',
  'Vukovje',
  'Vukovski Dol',
  'Vukovski Vrh',
  'Vurberk',
  'Vurmat - del',
  'Vuzenica',
  'Vuzmetinci',
  'Za Kalvarijo',
  'Zabava',
  'Zabavlje',
  'Zabiče',
  'Zabočevo',
  'Zabork',
  'Zaboršt',
  'Zaboršt pri Dolu',
  'Zaboršt pri Šentvidu',
  'Zabovci',
  'Zabrdje',
  'Zabrdo',
  'Zabrekve',
  'Zabreznica',
  'Zabreznik',
  'Zabrež',
  'Zabrežnik',
  'Zabukovica',
  'Zabukovje',
  'Zabukovje nad Sevnico',
  'Zabukovje pri Raki',
  'Začret',
  'Zadlaz-Čadrg',
  'Zadlaz-Žabče',
  'Zadlog',
  'Zadniki',
  'Zadnja vas',
  'Zadobje',
  'Zadobrova',
  'Zadolje',
  'Zadraga',
  'Zadrže',
  'Zafara',
  'Zagaj',
  'Zagaj pod Bočem',
  'Zagaj pri Ponikvi',
  'Zagajski Vrh',
  'Zagojiči',
  'Zagomila',
  'Zagon',
  'Zagora',
  'Zagorci',
  'Zagorica',
  'Zagorica nad Kamnikom',
  'Zagorica pri Čatežu',
  'Zagorica pri Dobrniču',
  'Zagorica pri Dolskem',
  'Zagorica pri Rovah',
  'Zagorica pri Velikem Gabru',
  'Zagorje',
  'Zagorje ob Savi',
  'Zagozd',
  'Zagozdac',
  'Zagrad',
  'Zagrad pri Otočcu',
  'Zagradec',
  'Zagradec pri Grosupljem',
  'Zagradišče',
  'Zagrajec',
  'Zagrič',
  'Zahomce',
  'Zahrib',
  'Zajasovnik - del',
  'Zajčje Polje',
  'Zajčji Vrh',
  'Zajčji Vrh pri Stopičah',
  'Zajelše',
  'Zajelšje',
  'Zakal',
  'Zakl',
  'Zaklanec',
  'Zakobiljek',
  'Zakojca',
  'Zakraj',
  'Zakriž',
  'Zala',
  'Zalči',
  'Zales',
  'Zali Breg',
  'Zali Log',
  'Zalisec',
  'Zalog',
  'Zalog pod Sv. Trojico',
  'Zalog pod Uršulo',
  'Zalog pri Cerkljah',
  'Zalog pri Kresnicah',
  'Zalog pri Moravčah',
  'Zalog pri Šempetru',
  'Zalog pri Škocjanu',
  'Zalog pri Škofljici',
  'Zaloka',
  'Zaloke',
  'Zalošče',
  'Zaloše',
  'Zaloška Gorica',
  'Založe',
  'Zamarkova',
  'Zameško',
  'Zamostec',
  'Zamušani',
  'Zaplana',
  'Zaplana - del',
  'Zaplanina',
  'Zapodje',
  'Zapoge',
  'Zapotok',
  'Zapreval',
  'Zapudje',
  'Zapuže',
  'Zapuže pri Kostelu',
  'Zapuže pri Ribnici',
  'Zarečica',
  'Zarečje',
  'Zasadi',
  'Zasap',
  'Zasavci',
  'Zasip',
  'Zastava',
  'Zastranje',
  'Zatolmin',
  'Zavine',
  'Zavinek',
  'Zavino',
  'Zavodice',
  'Zavodnje',
  'Zavrate',
  'Zavratec',
  'Zavrč',
  'Zavrh',
  'Zavrh nad Dobrno',
  'Zavrh pod Šmarno goro',
  'Zavrh pri Borovnici',
  'Zavrh pri Črnivcu',
  'Zavrh pri Galiciji',
  'Zavrh pri Trojanah',
  'Zavrhek',
  'Zavrstnik',
  'Završe',
  'Završe pri Dobjem',
  'Završe pri Grobelnem',
  'Završje',
  'Zavrtače',
  'Zazid',
  'Zbelovo',
  'Zbelovska Gora',
  'Zbigovci',
  'Zbilje',
  'Zbure',
  'Zdenska vas',
  'Zdole',
  'Zduša',
  'Zeče',
  'Zeče pri Bučah',
  'Zelen Breg',
  'Zelše',
  'Zemelj',
  'Zemono',
  'Zenkovci',
  'Zglavnica',
  'Zgonče',
  'Zgornja Bačkova',
  'Zgornja Bela',
  'Zgornja Besnica',
  'Zgornja Bistrica',
  'Zgornja Brežnica',
  'Zgornja Dobrava',
  'Zgornja Draga',
  'Zgornja Gorica',
  'Zgornja Hajdina',
  'Zgornja Jablanica',
  'Zgornja Javoršica',
  'Zgornja Jevnica',
  'Zgornja Kapla',
  'Zgornja Korena',
  'Zgornja Kostrivnica',
  'Zgornja Kungota',
  'Zgornja Lipnica',
  'Zgornja Ložnica',
  'Zgornja Luša',
  'Zgornja Nova vas',
  'Zgornja Orlica',
  'Zgornja Pohanca',
  'Zgornja Polskava',
  'Zgornja Pristava',
  'Zgornja Radovna',
  'Zgornja Rečica',
  'Zgornja Ročica',
  'Zgornja Selnica',
  'Zgornja Senarska',
  'Zgornja Senica',
  'Zgornja Slivnica',
  'Zgornja Sorica',
  'Zgornja Sveča',
  'Zgornja Ščavnica',
  'Zgornja Velka',
  'Zgornja Vižinga',
  'Zgornja Voličina',
  'Zgornje Bitnje',
  'Zgornje Danje',
  'Zgornje Dobrenje',
  'Zgornje Duplice',
  'Zgornje Duplje',
  'Zgornje Gameljne',
  'Zgornje Gorče',
  'Zgornje Gorje',
  'Zgornje Gradišče',
  'Zgornje Gruškovje',
  'Zgornje Grušovje',
  'Zgornje Grušovlje',
  'Zgornje Hlapje',
  'Zgornje Hoče',
  'Zgornje Jablane',
  'Zgornje Jarše',
  'Zgornje Jezersko',
  'Zgornje Konjišče',
  'Zgornje Koseze',
  'Zgornje Laze',
  'Zgornje Laže',
  'Zgornje Loke',
  'Zgornje Mladetiče',
  'Zgornje Negonje',
  'Zgornje Palovče',
  'Zgornje Partinje',
  'Zgornje Pirniče',
  'Zgornje Pobrežje',
  'Zgornje Poljčane',
  'Zgornje Prapreče',
  'Zgornje Prebukovje',
  'Zgornje Roje',
  'Zgornje Sečovo',
  'Zgornje Selce',
  'Zgornje Slemene',
  'Zgornje Stranje',
  'Zgornje Škofije',
  'Zgornje Tinsko',
  'Zgornje Verjane',
  'Zgornje Vetrno',
  'Zgornje Vodale',
  'Zgornje Vrtiče',
  'Zgornji Boč',
  'Zgornji Brnik',
  'Zgornji Čačič',
  'Zgornji Dražen Vrh',
  'Zgornji Duplek',
  'Zgornji Gabernik',
  'Zgornji Gasteraj',
  'Zgornji Hotič',
  'Zgornji Jakobski Dol',
  'Zgornji Janževski Vrh',
  'Zgornji Kamenščak',
  'Zgornji Kocjan',
  'Zgornji kozji Vrh',
  'Zgornji Lehen na Pohorju',
  'Zgornji Leskovec',
  'Zgornji Log',
  'Zgornji Motnik',
  'Zgornji Obrež',
  'Zgornji Otok',
  'Zgornji Petelinjek',
  'Zgornji Porčič',
  'Zgornji Prekar',
  'Zgornji Prhovec',
  'Zgornji Razbor',
  'Zgornji Slemen - del',
  'Zgornji Tuhinj',
  'Zgornji Tuštanj',
  'Zgornji Velovlek',
  'Zgornji Žerjavci',
  'Zgoša',
  'Zibika',
  'Zibiška vas',
  'Zidani Most',
  'Zilje',
  'Zimica',
  'Zlakova',
  'Zlateče',
  'Zlateče pri Šentjurju',
  'Zlatenek',
  'Zlati Rep',
  'Zlato Polje',
  'Zlatoličje',
  'Zloganje',
  'Zlogona Gora',
  'Zlogona vas',
  'Zminec',
  'Znojile',
  'Znojile pri Krki',
  'Znojile pri Studencu',
  'Zorenci',
  'Zreče',
  'Zrkovci',
  'Zvirče',
  'Zvodno',
  'Žabče',
  'Žabja vas',
  'Žabjek',
  'Žabjek v Podbočju',
  'Žablje',
  'Žabljek',
  'Žabnica',
  'Žadovinek',
  'Žaga',
  'Žagolič',
  'Žahenberc',
  'Žalec',
  'Žalna',
  'Žaloviče',
  'Žamenci',
  'Žapuže',
  'Žažar',
  'Ždinja vas',
  'Žebnik',
  'Žegar',
  'Žeje',
  'Žeje pri Komendi',
  'Žejno',
  'Želče',
  'Želebej',
  'Železne Dveri',
  'Železnica',
  'Železniki',
  'Železno',
  'Želimlje',
  'Željne',
  'Želodnik',
  'Ženavlje',
  'Ženik',
  'Ženje',
  'Žepina',
  'Žepovci',
  'Žerjav',
  'Žerjavin',
  'Žerjavka',
  'Žerovinci',
  'Žerovnica',
  'Žetale',
  'Žiberci',
  'Žibrše',
  'Žice',
  'Žiče',
  'Žiganja vas',
  'Žigon',
  'Žigrski Vrh',
  'Žihlava',
  'Žihovo selo',
  'Žikarce',
  'Žimarice',
  'Žiri',
  'Žirje',
  'Žirovnica',
  'Žirovski Vrh',
  'Žirovski Vrh Sv. Antona',
  'Žirovski Vrh Sv. Urbana',
  'Žirovše',
  'Žitence',
  'Žitkovci',
  'Žižki',
  'Žlabor',
  'Žlan',
  'Žlebe',
  'Žlebič',
  'Žrnova',
  'Žubejevo',
  'Žubina',
  'Žukovo',
  'Žuniči',
  'Župa',
  'Župančiči',
  'Županje Njive',
  'Župeča vas',
  'Župečja vas',
  'Župelevec',
  'Župeno',
  'Župetinci',
  'Žurge',
  'Žurkov Dol',
  'Žužemberk',
  'Žvab',
  'Žvabovo',
  'Žvarulje',
  'Žvirče',
];

export = settlements;
