name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ format('test{0}', (github.event.pull_request.head.repo.pushed_at || github.event.repository.pushed_at)) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: cd server && docker build . --file Dockerfile_tests --tag ${{ secrets.DOCKER_USERNAME }}/novice:$TIMESTAMP

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/novice:$TIMESTAMP

      - name: Set up Git
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "SenadSalkanovic2002"
          git config --global user.email "senad.salkanovic12@gmail.com"

      - name: Commit and push changes
        run: |
          cd server
          git add Dockerfile
          git commit -m "Update Dockerfile"
          git push origin development
