name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Running tests
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: npm run test

